#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""附录源码拼接 —— 环节⑪ 附录的代码部分由本脚本生成，不由 writer 手写。

动机：2026 CUMCM C 题的附录内联了 20 个源码模块共 7,058 行，并被反复重建 6 次
（每次重建都重新生成整份源码清单）。源码拼接是纯机械动作，交给脚本后
writer 只需写文件索引表与关键片段说明。

用法：
    python build_appendix.py --src <code/src> [--out <paper/sections/11-附录.md>]
    python build_appendix.py --src <code/src> --dry-run     # 只打印索引表，不写文件

无 --out 时只输出到 stdout（便于 writer 取索引表）。
"""

from __future__ import annotations

import argparse
import ast
import sys
from datetime import datetime
from pathlib import Path

# 跳过这些目录（缓存/虚拟环境/产物）。
# 注意：必须按**相对 src 的**路径段判断——标准布局是 outputs/mcm_xxx/code/src/，
# "outputs" 总会出现在绝对路径里，按绝对路径判会误杀全部文件。
SKIP_DIRS = {"__pycache__", ".ipynb_checkpoints", ".venv", "venv", ".git", "outputs"}
# 入口文件优先排在索引表最前
ENTRY_NAMES = ("main.py", "run_all.py", "run.py")


def first_sentence(path: Path) -> str:
    """取模块 docstring 的首句作为「作用」列；无 docstring 则退回首个注释行。"""
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return "（无法读取）"

    try:
        doc = ast.get_docstring(ast.parse(text))
    except SyntaxError:
        doc = None

    if doc:
        line = doc.strip().splitlines()[0].strip()
        return line[:60] + ("…" if len(line) > 60 else "")

    for raw in text.splitlines():
        stripped = raw.strip()
        if stripped.startswith("#") and not stripped.startswith("#!"):
            body = stripped.lstrip("#").strip()
            if body and not body.startswith("-*-"):
                return body[:60] + ("…" if len(body) > 60 else "")
    return "（无说明）"


def collect(src: Path) -> list[tuple[Path, str]]:
    """收集 .py 文件，入口文件置顶，其余按路径排序。"""
    files = [
        p
        for p in src.rglob("*.py")
        if not any(part in SKIP_DIRS for part in p.relative_to(src).parts)
    ]
    files.sort(key=lambda p: (p.name not in ENTRY_NAMES, str(p).lower()))
    return [(p, first_sentence(p)) for p in files]


def render(src: Path, entries: list[tuple[Path, str]], with_source: bool) -> str:
    total_lines = 0
    parts: list[str] = []

    parts.append("# 附录\n")
    parts.append("## 附录A 程序代码\n")
    parts.append(
        "> 全量源码见支撑材料；下表为文件索引，逐文件源码列于 A.1 之后。\n"
        "> 本附录由 `scripts/build_appendix.py` 生成，请勿手工编辑。\n"
    )

    parts.append("| 文件 | 作用 |")
    parts.append("|------|------|")
    for path, desc in entries:
        rel = path.relative_to(src).as_posix()
        parts.append(f"| `src/{rel}` | {desc} |")
    parts.append("")

    if not with_source:
        return "\n".join(parts)

    parts.append("## 附录A.1 源码清单\n")
    for path, _ in entries:
        rel = path.relative_to(src).as_posix()
        try:
            code = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError) as exc:
            parts.append(f"### `src/{rel}`\n\n（读取失败：{exc}）\n")
            continue
        n = code.count("\n") + (0 if code.endswith("\n") else 1)
        total_lines += n
        parts.append(f"### `src/{rel}`\n")
        parts.append(f"```python\n{code.rstrip()}\n```\n")

    return "\n".join(parts)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="拼接论文附录的程序代码部分")
    ap.add_argument("--src", required=True, help="代码目录，如 outputs/mcm_xxx/code/src")
    ap.add_argument("--out", help="输出 .md 路径；缺省只打印索引表到 stdout")
    ap.add_argument("--dry-run", action="store_true", help="不写文件，只打印索引表")
    args = ap.parse_args(argv)

    src = Path(args.src).resolve()
    if not src.is_dir():
        print(f"[build_appendix] 目录不存在：{src}", file=sys.stderr)
        return 1

    entries = collect(src)
    if not entries:
        print(f"[build_appendix] 未找到 .py 文件：{src}", file=sys.stderr)
        return 1

    # --out 给出且非 dry-run 时拼全量源码；否则只出索引表
    with_source = bool(args.out) and not args.dry_run
    text = render(src, entries, with_source)

    if with_source:
        out = Path(args.out)
        out.parent.mkdir(parents=True, exist_ok=True)
        header = f"<!-- generated by scripts/build_appendix.py at {datetime.now():%Y-%m-%d %H:%M:%S} -->\n"
        out.write_text(header + text, encoding="utf-8")
        total_lines = sum(
            p.read_text(encoding="utf-8").count("\n") for p, _ in entries
        )
        print(
            f"[build_appendix] {len(entries)} 个文件 / {total_lines} 行 → {out}",
            file=sys.stderr,
        )
    else:
        print(text)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
