#!/usr/bin/env python3
"""
考研英语完形填空高频1000词 — PDF生成脚本
===============================
按照词性与考点分类，适合系统记忆。
"""

from fpdf import FPDF
import os

# ── 中文字体路径 ──────────────────────────────────────────────
FONT_DIR = "C:/Windows/Fonts"
FONT_MAIN = os.path.join(FONT_DIR, "msyh.ttc")      # 微软雅黑
FONT_BOLD = os.path.join(FONT_DIR, "msyhbd.ttc")    # 微软雅黑粗体
FONT_HEAD = os.path.join(FONT_DIR, "simhei.ttf")    # 黑体
# 备用
if not os.path.exists(FONT_BOLD):
    FONT_BOLD = FONT_HEAD

# ── 分类词汇数据 ─────────────────────────────────────────────
# 格式: (英文, 词性, 中文释义)

CATEGORIES = [
    {
        "name": "一、逻辑关系词（连接词与过渡词）",
        "desc": "完形填空最常考的逻辑连接，决定文章起承转合",
        "words": [
            ("however", "conj./adv.", "然而，可是"),
            ("nevertheless", "adv.", "然而，不过"),
            ("nonetheless", "adv.", "尽管如此"),
            ("whereas", "conj.", "然而，鉴于"),
            ("while", "conj.", "当…时；然而"),
            ("although", "conj.", "虽然，尽管"),
            ("though", "conj./adv.", "虽然；不过"),
            ("despite", "prep.", "尽管，不管"),
            ("in spite of", "prep.", "尽管"),
            ("regardless of", "prep.", "不顾，不管"),
            ("furthermore", "adv.", "此外，而且"),
            ("moreover", "adv.", "而且，此外"),
            ("besides", "adv./prep.", "此外；除…之外"),
            ("in addition", "adv.", "此外"),
            ("likewise", "adv.", "同样地"),
            ("similarly", "adv.", "相似地"),
            ("conversely", "adv.", "相反地"),
            ("instead", "adv.", "反而，代替"),
            ("alternatively", "adv.", "或者，二者择一地"),
            ("otherwise", "adv./conj.", "否则；不然"),
            ("therefore", "adv.", "因此，所以"),
            ("thus", "adv.", "因此，从而"),
            ("hence", "adv.", "因此，由此"),
            ("consequently", "adv.", "因此，结果"),
            ("accordingly", "adv.", "相应地；因此"),
            ("as a result", "adv.", "结果是"),
            ("thereby", "adv.", "从而，由此"),
            ("so that", "conj.", "以便；所以"),
            ("in order that", "conj.", "为了"),
            ("provided", "conj.", "假如，以…为条件"),
            ("providing", "conj.", "假如"),
            ("suppose", "conj./v.", "假设；假定"),
            ("supposing", "conj.", "假使"),
            ("unless", "conj.", "除非，如果不"),
            ("given that", "conj.", "考虑到，鉴于"),
            ("considering", "prep./conj.", "考虑到"),
            ("whereas", "conj.", "鉴于；然而"),
            ("meanwhile", "adv.", "与此同时"),
            ("subsequently", "adv.", "随后，后来"),
            ("eventually", "adv.", "最终，终于"),
            ("ultimately", "adv.", "最终，根本上"),
            ("originally", "adv.", "最初，原来"),
            ("initially", "adv.", "起初，开始"),
            ("previously", "adv.", "以前，先前"),
            ("simultaneously", "adv.", "同时地"),
            ("concurrently", "adv.", "同时发生地"),
            ("notably", "adv.", "值得注意地"),
            ("particularly", "adv.", "特别地"),
            ("especially", "adv.", "尤其，特别"),
            ("specifically", "adv.", "具体地"),
            ("namely", "adv.", "即，也就是"),
            ("i.e.", "abbr.", "即，也就是说"),
            ("e.g.", "abbr.", "例如"),
            ("for instance", "adv.", "例如"),
            ("for example", "adv.", "例如"),
            ("such as", "prep.", "比如，诸如"),
            ("including", "prep.", "包括"),
            ("regarding", "prep.", "关于"),
            ("concerning", "prep.", "关于"),
            ("with respect to", "prep.", "关于，就…而论"),
            ("in terms of", "prep.", "就…而言"),
            ("in light of", "prep.", "鉴于，考虑到"),
            ("by contrast", "adv.", "相比之下"),
            ("on the contrary", "adv.", "相反地"),
            ("in contrast", "adv.", "对比之下"),
            ("on the other hand", "adv.", "另一方面"),
            ("in comparison", "adv.", "比较起来"),
            ("above all", "adv.", "最重要的是"),
            ("first and foremost", "adv.", "首要地"),
            ("most importantly", "adv.", "最重要的是"),
            ("indeed", "adv.", "确实，的确"),
            ("actually", "adv.", "实际上"),
            ("in fact", "adv.", "事实上"),
            ("as a matter of fact", "adv.", "事实上"),
            ("essentially", "adv.", "本质上"),
            ("basically", "adv.", "基本上"),
            ("fundamentally", "adv.", "根本上"),
            ("roughly", "adv.", "大致地"),
            ("approximately", "adv.", "大约"),
            ("about", "adv./prep.", "大约；关于"),
            ("in general", "adv.", "一般来说"),
            ("generally", "adv.", "通常，一般地"),
            ("overall", "adj./adv.", "总体的；总体上"),
            ("typically", "adv.", "典型地"),
            ("frequently", "adv.", "频繁地"),
            ("occasionally", "adv.", "偶尔"),
            ("rarely", "adv.", "很少，难得"),
            ("seldom", "adv.", "很少，不常"),
        ]
    },
    {
        "name": "二、高频动词",
        "desc": "完形填空核心动词，涵盖观点、变化、影响等语义场",
        "words": [
            ("abandon", "v.", "放弃；遗弃"),
            ("absorb", "v.", "吸收；吸引"),
            ("accelerate", "v.", "加速"),
            ("accept", "v.", "接受"),
            ("accommodate", "v.", "容纳；适应"),
            ("accompany", "v.", "陪伴；伴随"),
            ("accomplish", "v.", "完成，实现"),
            ("account for", "v.", "解释；占（比例）"),
            ("accumulate", "v.", "积累，积聚"),
            ("achieve", "v.", "达到，取得"),
            ("acknowledge", "v.", "承认；感谢"),
            ("acquire", "v.", "获得，学到"),
            ("adapt", "v.", "适应；改编"),
            ("address", "v.", "处理；向…讲话"),
            ("adjust", "v.", "调整，调节"),
            ("administer", "v.", "管理；执行"),
            ("adopt", "v.", "采用；收养"),
            ("advance", "v.", "前进；促进"),
            ("affect", "v.", "影响；感动"),
            ("afford", "v.", "负担得起；提供"),
            ("agree", "v.", "同意"),
            ("allocate", "v.", "分配，拨出"),
            ("alter", "v.", "改变，修改"),
            ("analyze", "v.", "分析"),
            ("announce", "v.", "宣布，通告"),
            ("answer", "v.", "回答；响应"),
            ("anticipate", "v.", "预期，期望"),
            ("appear", "v.", "出现；似乎"),
            ("apply", "v.", "应用；申请"),
            ("appreciate", "v.", "感激；欣赏"),
            ("approach", "v./n.", "接近；方法"),
            ("appropriate", "v./adj.", "拨出；适当的"),
            ("argue", "v.", "争论；主张"),
            ("arise", "v.", "出现，产生"),
            ("arrange", "v.", "安排"),
            ("articulate", "v./adj.", "明确表达；发音清晰的"),
            ("assemble", "v.", "集合；装配"),
            ("assess", "v.", "评估，评价"),
            ("assign", "v.", "分配；指定"),
            ("assist", "v.", "帮助，协助"),
            ("associate", "v.", "联系；联想"),
            ("assume", "v.", "假定；承担"),
            ("attach", "v.", "附上；使依恋"),
            ("attain", "v.", "获得，达到"),
            ("attempt", "v./n.", "尝试，企图"),
            ("attend", "v.", "出席；照料"),
            ("attract", "v.", "吸引"),
            ("attribute to", "v.", "归因于"),
            ("balance", "v./n.", "平衡"),
            ("bear", "v.", "忍受；承担"),
            ("behave", "v.", "行为，表现"),
            ("benefit", "v./n.", "受益；好处"),
            ("blame", "v.", "责备"),
            ("boost", "v./n.", "促进，提高"),
            ("calculate", "v.", "计算"),
            ("capture", "v.", "捕获；夺取"),
            ("cause", "v./n.", "引起；原因"),
            ("challenge", "v./n.", "挑战"),
            ("characterize", "v.", "以…为特征"),
            ("charge", "v./n.", "收费；指控；负责"),
            ("choose", "v.", "选择"),
            ("cite", "v.", "引用；引用"),
            ("claim", "v./n.", "声称；索赔"),
            ("clarify", "v.", "澄清，阐明"),
            ("classify", "v.", "分类"),
            ("collapse", "v./n.", "倒塌；崩溃"),
            ("combine", "v.", "结合"),
            ("commit", "v.", "犯（罪）；致力于"),
            ("communicate", "v.", "交流，沟通"),
            ("compare", "v.", "比较"),
            ("compel", "v.", "强迫，迫使"),
            ("compensate", "v.", "补偿，弥补"),
            ("compete", "v.", "竞争"),
            ("complain", "v.", "抱怨，投诉"),
            ("complete", "v./adj.", "完成；完整的"),
            ("compose", "v.", "组成；作曲"),
            ("comprehend", "v.", "理解，领悟"),
            ("concentrate", "v.", "集中；专注"),
            ("conclude", "v.", "结论；结束"),
            ("conduct", "v./n.", "进行；行为"),
            ("confine", "v.", "限制"),
            ("confirm", "v.", "确认，证实"),
            ("confront", "v.", "面对，遭遇"),
            ("connect", "v.", "连接"),
            ("consent", "v./n.", "同意，赞成"),
            ("conserve", "v.", "保存，保护"),
            ("consider", "v.", "考虑"),
            ("consist of", "v.", "由…组成"),
            ("consolidate", "v.", "巩固，加强"),
            ("constitute", "v.", "构成；设立"),
            ("construct", "v.", "建造；构建"),
            ("consult", "v.", "咨询；查阅"),
            ("consume", "v.", "消费，消耗"),
            ("contain", "v.", "包含；控制"),
            ("contend", "v.", "竞争；主张"),
            ("contribute to", "v.", "贡献；导致"),
            ("convert", "v.", "转换，转变"),
            ("convey", "v.", "传达；运送"),
            ("convince", "v.", "说服，使确信"),
            ("cooperate", "v.", "合作"),
            ("cope with", "v.", "应对，处理"),
            ("correspond", "v.", "对应；通信"),
            ("create", "v.", "创造"),
            ("cultivate", "v.", "培养；耕作"),
            ("debate", "v./n.", "辩论"),
            ("decay", "v./n.", "衰减；腐烂"),
            ("deceive", "v.", "欺骗"),
            ("decide", "v.", "决定"),
            ("decline", "v./n.", "下降；拒绝"),
            ("decrease", "v./n.", "减少"),
            ("dedicate", "v.", "致力于；奉献"),
            ("defeat", "v./n.", "打败，击败"),
            ("defend", "v.", "防御；辩护"),
            ("define", "v.", "定义"),
            ("deliver", "v.", "递送；发表"),
            ("demand", "v./n.", "要求；需求"),
            ("demonstrate", "v.", "展示；证明"),
            ("deny", "v.", "否认；拒绝"),
            ("depart", "v.", "离开；背离"),
            ("depend on", "v.", "依赖；取决于"),
            ("depict", "v.", "描绘，描述"),
            ("deposit", "v./n.", "存放；存款"),
            ("deprive", "v.", "剥夺"),
            ("derive", "v.", "源自；衍生"),
            ("deserve", "v.", "值得，应得"),
            ("design", "v./n.", "设计"),
            ("desire", "v./n.", "渴望"),
            ("destroy", "v.", "破坏，毁灭"),
            ("detect", "v.", "察觉；探测"),
            ("determine", "v.", "决定；测定"),
            ("develop", "v.", "发展；开发"),
            ("devote", "v.", "奉献，致力于"),
            ("differ", "v.", "不同，相异"),
            ("digest", "v./n.", "消化；文摘"),
            ("diminish", "v.", "减少，缩小"),
            ("disappear", "v.", "消失"),
            ("discover", "v.", "发现"),
            ("discriminate", "v.", "歧视；区分"),
            ("discuss", "v.", "讨论"),
            ("display", "v./n.", "展示；显示"),
            ("dispose", "v.", "处理；安排"),
            ("distinguish", "v.", "区分，辨别"),
            ("distort", "v.", "扭曲；歪曲"),
            ("distribute", "v.", "分配；分布"),
            ("disturb", "v.", "打扰，干扰"),
            ("dominate", "v.", "主导，支配"),
            ("doubt", "v./n.", "怀疑"),
            ("draft", "v./n.", "起草；草案"),
            ("draw", "v.", "画；拉；吸引"),
            ("duplicate", "v./adj./n.", "复制；复制的；副本"),
            ("economize", "v.", "节约，节省"),
            ("educate", "v.", "教育"),
            ("effect", "v./n.", "实现；效果"),
            ("elaborate", "v./adj.", "详述；精心的"),
            ("eliminate", "v.", "消除，根除"),
            ("embrace", "v.", "拥抱；包含"),
            ("emerge", "v.", "出现，浮现"),
            ("emphasize", "v.", "强调"),
            ("employ", "v.", "雇用；使用"),
            ("enable", "v.", "使能够"),
            ("encounter", "v./n.", "遭遇，遇到"),
            ("endure", "v.", "忍受；持久"),
            ("engage", "v.", "从事；吸引"),
            ("enhance", "v.", "提高，增强"),
            ("enjoy", "v.", "享受；享有"),
            ("ensure", "v.", "确保，保证"),
            ("establish", "v.", "建立；确立"),
            ("evaluate", "v.", "评估，评价"),
            ("evolve", "v.", "进化；演变"),
            ("examine", "v.", "检查；考试"),
            ("exceed", "v.", "超过，超越"),
            ("exchange", "v./n.", "交换；交流"),
            ("exclude", "v.", "排除"),
            ("execute", "v.", "执行；处决"),
            ("exert", "v.", "施加；发挥"),
            ("exhibit", "v./n.", "展览；展示"),
            ("expand", "v.", "扩展，膨胀"),
            ("expect", "v.", "期望，预期"),
            ("expel", "v.", "驱逐；开除"),
            ("experiment", "v./n.", "实验"),
            ("explain", "v.", "解释"),
            ("exploit", "v./n.", "开发；剥削"),
            ("explore", "v.", "探索；考察"),
            ("expose", "v.", "暴露；揭露"),
            ("extend", "v.", "延伸；扩展"),
            ("extract", "v./n.", "提取；摘录"),
            ("facilitate", "v.", "促进，使便利"),
            ("focus", "v./n.", "聚焦；焦点"),
            ("forbid", "v.", "禁止"),
            ("forecast", "v./n.", "预测，预报"),
            ("forge", "v.", "锻造；伪造"),
            ("form", "v./n.", "形成；形式"),
            ("formulate", "v.", "制定；明确表达"),
            ("found", "v.", "建立，创立"),
            ("generate", "v.", "产生，生成"),
            ("govern", "v.", "统治；管理"),
            ("guarantee", "v./n.", "保证，担保"),
            ("handle", "v./n.", "处理；把手"),
            ("happen", "v.", "发生"),
            ("harm", "v./n.", "伤害，损害"),
            ("hesitate", "v.", "犹豫"),
            ("highlight", "v./n.", "强调；亮点"),
            ("hinder", "v.", "阻碍，妨碍"),
            ("identify", "v.", "识别；确认"),
            ("ignore", "v.", "忽视，忽略"),
            ("illustrate", "v.", "说明；举例"),
            ("imagine", "v.", "想象"),
            ("imitate", "v.", "模仿"),
            ("implement", "v./n.", "实施；工具"),
            ("imply", "v.", "暗示，意味"),
            ("impose", "v.", "强加；征（税）"),
            ("impress", "v.", "给…深刻印象"),
            ("improve", "v.", "改善，提高"),
            ("incorporate", "v.", "合并；包含"),
            ("indicate", "v.", "表明；指示"),
            ("individualize", "v.", "个性化"),
            ("induce", "v.", "诱导；引起"),
            ("infer", "v.", "推断，推理"),
            ("influence", "v./n.", "影响"),
            ("inform", "v.", "通知；告知"),
            ("inhabit", "v.", "居住于"),
            ("inherit", "v.", "继承"),
            ("initiate", "v.", "开始；发起"),
            ("inject", "v.", "注射；注入"),
            ("innovate", "v.", "创新，革新"),
            ("inquire", "v.", "询问，查询"),
            ("insert", "v.", "插入"),
            ("insist", "v.", "坚持"),
            ("inspect", "v.", "检查，审视"),
            ("inspire", "v.", "激励；启发"),
            ("install", "v.", "安装；就职"),
            ("institute", "v./n.", "建立；机构"),
            ("instruct", "v.", "指导；命令"),
            ("integrate", "v.", "整合，一体化"),
            ("intend", "v.", "打算，意图"),
            ("interact", "v.", "互动；相互作用"),
            ("interpret", "v.", "解释；口译"),
            ("intervene", "v.", "干预；介入"),
            ("introduce", "v.", "介绍；引入"),
            ("invest", "v.", "投资；投入"),
            ("investigate", "v.", "调查"),
            ("involve", "v.", "涉及；使参与"),
            ("isolate", "v.", "隔离；孤立"),
            ("judge", "v./n.", "判断；法官"),
            ("justify", "v.", "证明…正当"),
            ("launch", "v./n.", "发射；发起"),
            ("maintain", "v.", "维持；主张"),
            ("manipulate", "v.", "操纵；操作"),
            ("manufacture", "v./n.", "制造"),
            ("measure", "v./n.", "测量；措施"),
            ("merge", "v.", "合并，融合"),
            ("monitor", "v./n.", "监控；监视器"),
            ("motivate", "v.", "激励；激发"),
            ("negotiate", "v.", "谈判，协商"),
            ("obey", "v.", "服从，遵守"),
            ("object", "v.", "反对"),
            ("observe", "v.", "观察；遵守"),
            ("obtain", "v.", "获得，得到"),
            ("occupy", "v.", "占据；使忙于"),
            ("operate", "v.", "操作；经营"),
            ("oppose", "v.", "反对，对抗"),
            ("organize", "v.", "组织"),
            ("originate", "v.", "起源；创始"),
            ("overcome", "v.", "克服"),
            ("overlook", "v.", "俯瞰；忽视"),
            ("participate", "v.", "参与"),
            ("perceive", "v.", "感知；认为"),
            ("perform", "v.", "执行；表演"),
            ("persist", "v.", "坚持；持续"),
            ("persuade", "v.", "说服"),
            ("possess", "v.", "拥有"),
            ("predict", "v.", "预测"),
            ("prefer", "v.", "偏好，更喜欢"),
            ("present", "v./adj./n.", "呈现；目前的；礼物"),
            ("preserve", "v.", "保存；保护"),
            ("prevent", "v.", "阻止，预防"),
            ("proceed", "v.", "继续进行"),
            ("produce", "v./n.", "生产；农产品"),
            ("profit", "v./n.", "获利；利润"),
            ("prohibit", "v.", "禁止"),
            ("promote", "v.", "促进；晋升"),
            ("propose", "v.", "提议；求婚"),
            ("prosper", "v.", "繁荣，成功"),
            ("protest", "v./n.", "抗议；反对"),
            ("pursue", "v.", "追求；从事"),
            ("qualify", "v.", "使合格；限定"),
            ("quantify", "v.", "量化"),
            ("question", "v./n.", "质疑；问题"),
            ("quit", "v.", "放弃；辞职"),
            ("rank", "v./n.", "排名；等级"),
            ("rate", "v./n.", "评价；率"),
            ("react", "v.", "反应"),
            ("recognize", "v.", "认出；承认"),
            ("recommend", "v.", "推荐；建议"),
            ("recover", "v.", "恢复；弥补"),
            ("rectify", "v.", "纠正，矫正"),
            ("reduce", "v.", "减少，降低"),
            ("reflect", "v.", "反射；反映；思考"),
            ("reform", "v./n.", "改革"),
            ("regulate", "v.", "调节；管理"),
            ("reject", "v.", "拒绝；排斥"),
            ("relate", "v.", "关联；叙述"),
            ("release", "v./n.", "释放；发布"),
            ("rely on", "v.", "依赖，信赖"),
            ("remain", "v.", "保持；剩余"),
            ("remedy", "v./n.", "补救；治疗"),
            ("remove", "v.", "移除；消除"),
            ("render", "v.", "使成为；给予"),
            ("replace", "v.", "代替，取代"),
            ("reproduce", "v.", "繁殖；复制"),
            ("request", "v./n.", "请求，要求"),
            ("require", "v.", "需要；要求"),
            ("rescue", "v./n.", "营救"),
            ("resemble", "v.", "像，相似"),
            ("reserve", "v./n.", "保留；储备"),
            ("resolve", "v.", "解决；决心"),
            ("resort to", "v.", "求助于；诉诸"),
            ("respond", "v.", "回应，响应"),
            ("restore", "v.", "恢复；修复"),
            ("restrict", "v.", "限制，约束"),
            ("result in", "v.", "导致"),
            ("retain", "v.", "保留，保持"),
            ("reveal", "v.", "揭露；显示"),
            ("reverse", "v./adj./n.", "逆转；相反的；反面"),
            ("revise", "v.", "修订；复习"),
            ("revive", "v.", "复兴；苏醒"),
            ("reward", "v./n.", "奖励；报酬"),
            ("sacrifice", "v./n.", "牺牲"),
            ("satisfy", "v.", "满足；使满意"),
            ("secure", "v./adj.", "获得；安全的"),
            ("seek", "v.", "寻求；寻找"),
            ("select", "v./adj.", "选择；精选的"),
            ("separate", "v./adj.", "分离；分开的"),
            ("settle", "v.", "解决；定居"),
            ("signal", "v./n.", "发出信号；信号"),
            ("simplify", "v.", "简化"),
            ("solve", "v.", "解决"),
            ("specialize", "v.", "专门研究"),
            ("specify", "v.", "指定；详述"),
            ("sponsor", "v./n.", "赞助；主办方"),
            ("stabilize", "v.", "使稳定"),
            ("stimulate", "v.", "刺激；激励"),
            ("strategy", "n.", "策略，战略"),
            ("strengthen", "v.", "加强，增强"),
            ("stress", "v./n.", "强调；压力"),
            ("structure", "v./n.", "构建；结构"),
            ("struggle", "v./n.", "挣扎；斗争"),
            ("substitute", "v./n.", "替代；替代品"),
            ("succeed", "v.", "成功；接替"),
            ("summarize", "v.", "总结，概述"),
            ("supplement", "v./n.", "补充；附录"),
            ("supply", "v./n.", "供应；供给"),
            ("support", "v./n.", "支持；资助"),
            ("suppose", "v.", "假设；认为"),
            ("suppress", "v.", "压制；抑制"),
            ("surround", "v.", "包围，围绕"),
            ("survey", "v./n.", "调查；测量"),
            ("survive", "v.", "幸存；生存"),
            ("suspect", "v./n./adj.", "怀疑；嫌疑犯；可疑的"),
            ("sustain", "v.", "维持；支撑"),
            ("symbolize", "v.", "象征"),
            ("tackle", "v.", "处理；对付"),
            ("tend", "v.", "倾向；照料"),
            ("terminate", "v.", "终止，结束"),
            ("testify", "v.", "作证；证明"),
            ("trace", "v./n.", "追踪；痕迹"),
            ("transform", "v.", "转变，改造"),
            ("transmit", "v.", "传输；传播"),
            ("trap", "v./n.", "设陷阱；陷阱"),
            ("treat", "v./n.", "对待；治疗；款待"),
            ("trigger", "v./n.", "触发；扳机"),
            ("undergo", "v.", "经历，遭受"),
            ("undertake", "v.", "承担；从事"),
            ("utilize", "v.", "利用"),
            ("vanish", "v.", "消失，消散"),
            ("verify", "v.", "验证，核实"),
            ("violate", "v.", "违反；侵犯"),
            ("virtue", "n.", "美德；优点"),
            ("volunteer", "v./n.", "自愿；志愿者"),
            ("withdraw", "v.", "撤回；提取"),
            ("withstand", "v.", "承受，抵挡"),
            ("witness", "v./n.", "目击；证人"),
        ]
    },
    {
        "name": "三、高频名词",
        "desc": "完形填空常考名词，涵盖抽象概念、社会现象、学术术语",
        "words": [
            ("ability", "n.", "能力"),
            ("absence", "n.", "缺席；缺乏"),
            ("abuse", "n./v.", "滥用；虐待"),
            ("access", "n./v.", "通道；访问"),
            ("account", "n./v.", "账户；说明"),
            ("achievement", "n.", "成就，成绩"),
            ("acquisition", "n.", "获得；习得"),
            ("advantage", "n.", "优势，有利条件"),
            ("adventure", "n.", "冒险"),
            ("advocate", "n./v.", "提倡者；提倡"),
            ("agenda", "n.", "议程"),
            ("agreement", "n.", "协议；同意"),
            ("alternative", "n./adj.", "替代方案；替代的"),
            ("ambition", "n.", "雄心；野心"),
            ("analysis", "n.", "分析"),
            ("ancestor", "n.", "祖先"),
            ("anxiety", "n.", "焦虑"),
            ("appearance", "n.", "出现；外貌"),
            ("application", "n.", "应用；申请"),
            ("appointment", "n.", "任命；约会"),
            ("appreciation", "n.", "感激；欣赏"),
            ("approach", "n.", "方法；途径"),
            ("approval", "n.", "批准；赞成"),
            ("argument", "n.", "争论；论点"),
            ("arrangement", "n.", "安排"),
            ("aspect", "n.", "方面"),
            ("assessment", "n.", "评估"),
            ("assignment", "n.", "任务；分配"),
            ("assistance", "n.", "援助，帮助"),
            ("association", "n.", "协会；关联"),
            ("atmosphere", "n.", "大气；氛围"),
            ("attitude", "n.", "态度"),
            ("attraction", "n.", "吸引；景点"),
            ("authority", "n.", "权威；当局"),
            ("availability", "n.", "可用性"),
            ("awareness", "n.", "意识；知道"),
            ("barrier", "n.", "障碍"),
            ("basis", "n.", "基础；根据"),
            ("behavior", "n.", "行为"),
            ("benefit", "n.", "利益；好处"),
            ("boundary", "n.", "边界"),
            ("burden", "n.", "负担"),
            ("campaign", "n./v.", "运动；战役"),
            ("capacity", "n.", "能力；容量"),
            ("category", "n.", "类别"),
            ("certificate", "n.", "证书，证明"),
            ("challenge", "n.", "挑战"),
            ("character", "n.", "性格；角色；字符"),
            ("characteristic", "n./adj.", "特征；特有的"),
            ("circumstance", "n.", "环境；情况"),
            ("citizen", "n.", "公民"),
            ("civilization", "n.", "文明"),
            ("climate", "n.", "气候；风气"),
            ("coincidence", "n.", "巧合"),
            ("command", "n./v.", "命令；指挥"),
            ("comment", "n./v.", "评论"),
            ("commitment", "n.", "承诺；奉献"),
            ("communication", "n.", "沟通；交流"),
            ("community", "n.", "社区；共同体"),
            ("comparison", "n.", "比较"),
            ("compensation", "n.", "补偿；赔偿"),
            ("competition", "n.", "竞争；比赛"),
            ("complexity", "n.", "复杂性"),
            ("component", "n./adj.", "组件；组成的"),
            ("concentrate", "v./n.", "专注；浓缩物"),
            ("concentration", "n.", "浓度；专注"),
            ("concept", "n.", "概念"),
            ("concern", "n./v.", "关心；担忧"),
            ("condition", "n.", "条件；状况"),
            ("confidence", "n.", "信心"),
            ("conflict", "n./v.", "冲突"),
            ("connection", "n.", "连接；联系"),
            ("consciousness", "n.", "意识；知觉"),
            ("consequence", "n.", "结果，后果"),
            ("conservation", "n.", "保护；保存"),
            ("consideration", "n.", "考虑；体谅"),
            ("contribution", "n.", "贡献"),
            ("control", "n./v.", "控制"),
            ("controversy", "n.", "争议"),
            ("convenience", "n.", "便利"),
            ("convention", "n.", "惯例；大会"),
            ("conviction", "n.", "定罪；信念"),
            ("cooperation", "n.", "合作"),
            ("coordination", "n.", "协调"),
            ("creativity", "n.", "创造力"),
            ("crisis", "n.", "危机"),
            ("criterion", "n.", "标准（pl. criteria）"),
            ("curiosity", "n.", "好奇心"),
            ("damage", "n./v.", "损害"),
            ("decade", "n.", "十年"),
            ("decision", "n.", "决定"),
            ("declaration", "n.", "宣言；声明"),
            ("decline", "n./v.", "下降；衰退"),
            ("defense", "n.", "防御；辩护"),
            ("definition", "n.", "定义"),
            ("demand", "n./v.", "需求；要求"),
            ("democracy", "n.", "民主"),
            ("demonstration", "n.", "演示；示威"),
            ("departure", "n.", "离开；背离"),
            ("dependence", "n.", "依赖"),
            ("description", "n.", "描述"),
            ("desire", "n./v.", "渴望"),
            ("destination", "n.", "目的地"),
            ("destruction", "n.", "破坏，毁灭"),
            ("determination", "n.", "决心；决定"),
            ("development", "n.", "发展"),
            ("device", "n.", "设备；手段"),
            ("disadvantage", "n.", "劣势，不利"),
            ("disaster", "n.", "灾难"),
            ("discipline", "n./v.", "纪律；学科；训练"),
            ("discovery", "n.", "发现"),
            ("discrimination", "n.", "歧视；辨别"),
            ("discussion", "n.", "讨论"),
            ("disorder", "n.", "混乱；失调"),
            ("display", "n./v.", "展示；显示"),
            ("dispute", "n./v.", "争端；争论"),
            ("distribution", "n.", "分配；分布"),
            ("diversity", "n.", "多样性"),
            ("document", "n./v.", "文件；记录"),
            ("domestic", "adj.", "国内的；家庭的"),
            ("dominance", "n.", "主导；优势"),
            ("draft", "n./v.", "草案；起草"),
            ("economy", "n.", "经济"),
            ("education", "n.", "教育"),
            ("effect", "n.", "效果；影响"),
            ("efficiency", "n.", "效率"),
            ("effort", "n.", "努力"),
            ("element", "n.", "元素；要素"),
            ("emergency", "n.", "紧急情况"),
            ("emotion", "n.", "情感，情绪"),
            ("emphasis", "n.", "强调；重点"),
            ("employee", "n.", "雇员"),
            ("employer", "n.", "雇主"),
            ("employment", "n.", "就业；雇用"),
            ("encounter", "n./v.", "遭遇"),
            ("encouragement", "n.", "鼓励"),
            ("energy", "n.", "能量；精力"),
            ("enforcement", "n.", "执行；强制"),
            ("engagement", "n.", "参与；订婚"),
            ("environment", "n.", "环境"),
            ("equality", "n.", "平等"),
            ("equipment", "n.", "设备；装备"),
            ("essence", "n.", "本质"),
            ("establishment", "n.", "建立；机构"),
            ("estimate", "n./v.", "估计"),
            ("evaluation", "n.", "评价"),
            ("evidence", "n.", "证据"),
            ("evolution", "n.", "进化；演变"),
            ("exception", "n.", "例外"),
            ("excess", "n./adj.", "过量；额外的"),
            ("exchange", "n./v.", "交换；兑换"),
            ("existence", "n.", "存在"),
            ("expansion", "n.", "扩展；膨胀"),
            ("expectation", "n.", "期望"),
            ("expense", "n.", "花费；代价"),
            ("experience", "n./v.", "经验；经历"),
            ("experiment", "n./v.", "实验"),
            ("expert", "n./adj.", "专家；专业的"),
            ("explanation", "n.", "解释"),
            ("exploration", "n.", "探索"),
            ("exposure", "n.", "暴露；接触"),
            ("extension", "n.", "延伸；扩展"),
            ("extent", "n.", "程度；范围"),
            ("extreme", "n./adj.", "极端；极端的"),
            ("facility", "n.", "设施；便利"),
            ("factor", "n.", "因素"),
            ("failure", "n.", "失败；故障"),
            ("fairness", "n.", "公平"),
            ("faith", "n.", "信仰；信任"),
            ("feature", "n./v.", "特征；以…为特色"),
            ("feedback", "n.", "反馈"),
            ("flexibility", "n.", "灵活性"),
            ("focus", "n./v.", "焦点；聚焦"),
            ("force", "n./v.", "力量；强迫"),
            ("formation", "n.", "形成；队形"),
            ("fortune", "n.", "财富；运气"),
            ("framework", "n.", "框架；结构"),
            ("frequency", "n.", "频率"),
            ("function", "n./v.", "功能；运作"),
            ("fundamental", "n./adj.", "基本原理；基本的"),
            ("generation", "n.", "一代；产生"),
            ("goal", "n.", "目标"),
            ("grant", "n./v.", "拨款；准予"),
            ("guarantee", "n./v.", "保证"),
            ("guideline", "n.", "指南；方针"),
            ("harmony", "n.", "和谐；融洽"),
            ("heritage", "n.", "遗产；传统"),
            ("hierarchy", "n.", "等级制度"),
            ("identification", "n.", "识别；身份证明"),
            ("identity", "n.", "身份；同一性"),
            ("illustration", "n.", "说明；插图"),
            ("imagination", "n.", "想象；创造力"),
            ("impact", "n./v.", "影响；冲击"),
            ("implementation", "n.", "实施"),
            ("implication", "n.", "含义；影响"),
            ("importance", "n.", "重要性"),
            ("imposition", "n.", "强加；征税"),
            ("impression", "n.", "印象"),
            ("improvement", "n.", "改善，改进"),
            ("incentive", "n.", "激励；刺激"),
            ("incident", "n.", "事件"),
            ("inclusion", "n.", "包含"),
            ("income", "n.", "收入"),
            ("independence", "n.", "独立"),
            ("indication", "n.", "迹象；指示"),
            ("individual", "n./adj.", "个人；个人的"),
            ("industry", "n.", "工业；行业"),
            ("inequality", "n.", "不平等"),
            ("inflation", "n.", "通货膨胀"),
            ("influence", "n./v.", "影响"),
            ("information", "n.", "信息"),
            ("initiative", "n.", "主动性；倡议"),
            ("innovation", "n.", "创新"),
            ("institution", "n.", "机构；制度"),
            ("instruction", "n.", "指令；说明；教学"),
            ("instrument", "n.", "工具；乐器"),
            ("insurance", "n.", "保险"),
            ("integration", "n.", "整合，融合"),
            ("integrity", "n.", "正直；完整"),
            ("intelligence", "n.", "智力；情报"),
            ("intensity", "n.", "强度"),
            ("intention", "n.", "意图"),
            ("interaction", "n.", "互动；交互"),
            ("interest", "n./v.", "兴趣；利息"),
            ("interpretation", "n.", "解释；口译"),
            ("intervention", "n.", "干预；介入"),
            ("introduction", "n.", "介绍；引言"),
            ("invasion", "n.", "入侵"),
            ("investigation", "n.", "调查"),
            ("investment", "n.", "投资"),
            ("involvement", "n.", "参与；卷入"),
            ("isolation", "n.", "隔离；孤立"),
            ("judgment", "n.", "判断；判决"),
            ("justice", "n.", "正义；司法"),
            ("justification", "n.", "辩护；正当理由"),
            ("knowledge", "n.", "知识；了解"),
            ("label", "n./v.", "标签；标注"),
            ("labor", "n./v.", "劳动；劳动力"),
            ("landscape", "n.", "景观；格局"),
            ("launch", "n./v.", "发射；启动"),
            ("leadership", "n.", "领导力"),
            ("leak", "n./v.", "泄漏"),
            ("legislation", "n.", "立法；法规"),
            ("legitimacy", "n.", "合法性"),
            ("liberty", "n.", "自由"),
            ("likelihood", "n.", "可能性"),
            ("limitation", "n.", "限制；局限"),
            ("literacy", "n.", "读写能力"),
            ("literature", "n.", "文学；文献"),
            ("maintenance", "n.", "维护；保养"),
            ("management", "n.", "管理；管理层"),
            ("manipulation", "n.", "操纵；操作"),
            ("manufacturer", "n.", "制造商"),
            ("mechanism", "n.", "机制；机理"),
            ("medium", "n./adj.", "媒介；中等的"),
            ("membership", "n.", "会员资格"),
            ("memory", "n.", "记忆；回忆"),
            ("mention", "n./v.", "提及"),
            ("minority", "n.", "少数；少数民族"),
            ("mission", "n.", "使命；任务"),
            ("mobility", "n.", "流动性"),
            ("modification", "n.", "修改；修正"),
            ("monopoly", "n.", "垄断"),
            ("morality", "n.", "道德"),
            ("motivation", "n.", "动机"),
            ("movement", "n.", "运动；移动"),
            ("mystery", "n.", "神秘"),
            ("necessity", "n.", "必需品；必要性"),
            ("negotiation", "n.", "谈判"),
            ("network", "n.", "网络"),
            ("norm", "n.", "规范；标准"),
            ("notion", "n.", "概念；看法"),
            ("obligation", "n.", "义务；职责"),
            ("observation", "n.", "观察"),
            ("obstacle", "n.", "障碍"),
            ("occupation", "n.", "职业；占领"),
            ("occurrence", "n.", "发生；事件"),
            ("operation", "n.", "操作；手术"),
            ("opportunity", "n.", "机会"),
            ("opposition", "n.", "反对"),
            ("option", "n.", "选择"),
            ("organization", "n.", "组织；机构"),
            ("orientation", "n.", "方向；定位"),
            ("outcome", "n.", "结果"),
            ("output", "n.", "产出；输出"),
            ("outlook", "n.", "观点；展望"),
            ("overview", "n.", "概述"),
        ]
    },
    {
        "name": "四、高频形容词",
        "desc": "完形填空常考形容词，用于态度、判断和描述",
        "words": [
            ("absolute", "adj.", "绝对的；完全的"),
            ("abstract", "adj./n./v.", "抽象的；摘要；提取"),
            ("abundant", "adj.", "丰富的，充足的"),
            ("accurate", "adj.", "精确的"),
            ("adequate", "adj.", "足够的；适当的"),
            ("aggressive", "adj.", "侵略的；有进取心的"),
            ("ambiguous", "adj.", "模棱两可的"),
            ("ambitious", "adj.", "有雄心的；有野心的"),
            ("annual", "adj.", "年度的"),
            ("apparent", "adj.", "明显的；表面的"),
            ("appropriate", "adj.", "适当的"),
            ("artificial", "adj.", "人工的；虚假的"),
            ("available", "adj.", "可获得的；有空的"),
            ("aware", "adj.", "意识到；知道的"),
            ("beneficial", "adj.", "有益的"),
            ("bound", "adj./v.", "一定的；受约束的；跳跃"),
            ("brief", "adj./v./n.", "简短的；简报；摘要"),
            ("capable", "adj.", "有能力的"),
            ("causal", "adj.", "因果的"),
            ("certain", "adj.", "确定的；某个"),
            ("chronic", "adj.", "慢性的；长期的"),
            ("civil", "adj.", "公民的；民用的"),
            ("classic", "adj./n.", "经典的；经典作品"),
            ("cognitive", "adj.", "认知的"),
            ("collective", "adj./n.", "集体的；集体"),
            ("commercial", "adj./n.", "商业的；广告"),
            ("common", "adj.", "常见的；共同的"),
            ("comparable", "adj.", "可比较的"),
            ("comparative", "adj.", "比较的；相对的"),
            ("compatible", "adj.", "兼容的"),
            ("competitive", "adj.", "有竞争力的"),
            ("comprehensive", "adj.", "全面的；综合的"),
            ("compulsory", "adj.", "强制性的"),
            ("confident", "adj.", "自信的"),
            ("conscientious", "adj.", "认真负责的"),
            ("conscious", "adj.", "有意识的；自觉的"),
            ("consecutive", "adj.", "连续的"),
            ("conservative", "adj./n.", "保守的；保守派"),
            ("considerable", "adj.", "相当大的；重要的"),
            ("consistent", "adj.", "一致的；始终如一的"),
            ("constant", "adj./n.", "不变的；常数"),
            ("contemporary", "adj./n.", "当代的；同代人"),
            ("content", "adj./n./v.", "满意的；内容；使满足"),
            ("controversial", "adj.", "有争议的"),
            ("conventional", "adj.", "传统的；常规的"),
            ("crucial", "adj.", "关键的"),
            ("curious", "adj.", "好奇的"),
            ("current", "adj./n.", "当前的；电流"),
            ("dangerous", "adj.", "危险的"),
            ("dazzling", "adj.", "耀眼的；令人惊叹的"),
            ("decent", "adj.", "体面的；相当好的"),
            ("defensive", "adj.", "防御的"),
            ("definite", "adj.", "明确的"),
            ("delicate", "adj.", "精细的；脆弱的"),
            ("dependent", "adj.", "依赖的"),
            ("desirable", "adj.", "值得拥有的"),
            ("desperate", "adj.", "绝望的；拼命的"),
            ("destructive", "adj.", "破坏性的"),
            ("determined", "adj.", "坚定的"),
            ("digital", "adj.", "数字的"),
            ("diligent", "adj.", "勤奋的"),
            ("direct", "adj./v./adv.", "直接的；指导；直接地"),
            ("distinct", "adj.", "不同的；明显的"),
            ("distinctive", "adj.", "有区别的；有特色的"),
            ("diverse", "adj.", "多样的"),
            ("domestic", "adj.", "国内的；家庭的"),
            ("dominant", "adj.", "占主导的"),
            ("dramatic", "adj.", "戏剧性的；巨大的"),
            ("drastic", "adj.", "激烈的；严厉的"),
            ("dynamic", "adj./n.", "动态的；动力"),
            ("economic", "adj.", "经济的"),
            ("economical", "adj.", "节约的"),
            ("effective", "adj.", "有效的"),
            ("efficient", "adj.", "高效的"),
            ("elaborate", "adj./v.", "精心的；详述"),
            ("elegant", "adj.", "优雅的"),
            ("eligible", "adj.", "合格的"),
            ("emergent", "adj.", "新兴的"),
            ("emotional", "adj.", "情绪的"),
            ("empirical", "adj.", "经验的；实证的"),
            ("encouraging", "adj.", "令人鼓舞的"),
            ("enormous", "adj.", "巨大的"),
            ("enthusiastic", "adj.", "热情的"),
            ("entire", "adj.", "整个的"),
            ("equivalent", "adj./n.", "等价的；等价物"),
            ("essential", "adj./n.", "必要的；要素"),
            ("ethnic", "adj.", "种族的"),
            ("evaluate", "v.", "评估"),
            ("eventual", "adj.", "最终的"),
            ("evident", "adj.", "明显的"),
            ("evil", "adj./n.", "邪恶的；罪恶"),
            ("exact", "adj.", "确切的"),
            ("excellent", "adj.", "优秀的"),
            ("exceptional", "adj.", "例外的；杰出的"),
            ("excessive", "adj.", "过度的"),
            ("exclusive", "adj.", "排他的；独有的"),
            ("executive", "adj./n.", "执行的；高管"),
            ("exhausted", "adj.", "筋疲力尽的"),
            ("existing", "adj.", "现有的"),
            ("explicit", "adj.", "明确的"),
            ("extraordinary", "adj.", "非凡的"),
            ("extreme", "adj./n.", "极端的；极端"),
            ("faint", "adj./v.", "微弱的；昏厥"),
            ("fair", "adj./n.", "公平的；展会"),
            ("faithful", "adj.", "忠诚的"),
            ("false", "adj.", "错误的；假的"),
            ("familiar", "adj.", "熟悉的"),
            ("fashionable", "adj.", "时尚的"),
            ("fatal", "adj.", "致命的"),
            ("favorable", "adj.", "有利的；赞成的"),
            ("feasible", "adj.", "可行的"),
            ("feminine", "adj.", "女性的"),
            ("fertile", "adj.", "肥沃的；富饶的"),
            ("financial", "adj.", "金融的；财务的"),
            ("flexible", "adj.", "灵活的"),
            ("foreign", "adj.", "外国的"),
            ("formal", "adj.", "正式的"),
            ("former", "adj./n.", "前者的；前者"),
            ("fragile", "adj.", "脆弱的"),
            ("frequent", "adj./v.", "频繁的；常去"),
            ("fundamental", "adj./n.", "基本的；基本原理"),
            ("further", "adj./adv./v.", "更远的；促进"),
            ("generous", "adj.", "慷慨的"),
            ("genetic", "adj.", "基因的；遗传的"),
            ("genuine", "adj.", "真正的；真诚的"),
            ("global", "adj.", "全球的"),
            ("gradual", "adj.", "逐渐的"),
            ("grateful", "adj.", "感激的"),
            ("gross", "adj./n./v.", "总的；毛的；总额"),
            ("guilty", "adj.", "有罪的；内疚的"),
            ("harmful", "adj.", "有害的"),
            ("harmonious", "adj.", "和谐的"),
            ("harsh", "adj.", "严厉的；严酷的"),
            ("healthful", "adj.", "有益健康的"),
            ("helpful", "adj.", "有帮助的"),
            ("hesitant", "adj.", "犹豫的"),
            ("hidden", "adj.", "隐藏的"),
            ("hollow", "adj./v.", "中空的；掏空"),
            ("honest", "adj.", "诚实的"),
            ("hopeful", "adj.", "有希望的"),
            ("horizontal", "adj.", "水平的"),
            ("hostile", "adj.", "敌对的"),
            ("humble", "adj.", "谦逊的"),
            ("identical", "adj.", "完全相同的"),
            ("identifiable", "adj.", "可辨认的"),
            ("ignorant", "adj.", "无知的"),
            ("illegal", "adj.", "非法的"),
            ("imaginary", "adj.", "想象的；虚构的"),
            ("immediate", "adj.", "立即的；直接的"),
            ("immense", "adj.", "巨大的"),
            ("imminent", "adj.", "迫近的"),
            ("impartial", "adj.", "公正的"),
            ("implement", "v./n.", "实施；工具"),
            ("implicit", "adj.", "隐含的"),
            ("impossible", "adj.", "不可能的"),
            ("impressive", "adj.", "令人印象深刻的"),
            ("inadequate", "adj.", "不充分的"),
            ("inappropriate", "adj.", "不适当的"),
            ("inclusive", "adj.", "包容的"),
            ("inconsistent", "adj.", "不一致的"),
            ("increasing", "adj.", "越来越多的"),
            ("incredible", "adj.", "难以置信的"),
            ("independent", "adj.", "独立的"),
            ("indirect", "adj.", "间接的"),
            ("indispensable", "adj.", "不可或缺的"),
            ("individual", "adj./n.", "个人的；个人"),
            ("inevitable", "adj.", "不可避免的"),
            ("influential", "adj.", "有影响力的"),
            ("informal", "adj.", "非正式的"),
            ("inherent", "adj.", "固有的；内在的"),
            ("initial", "adj./n.", "最初的；首字母"),
            ("innocent", "adj.", "无辜的；天真的"),
            ("innovative", "adj.", "创新的"),
            ("instant", "adj./n.", "立即的；瞬间"),
            ("institutional", "adj.", "制度的；机构的"),
            ("instrumental", "adj.", "起重要作用的"),
            ("intellectual", "adj./n.", "智力的；知识分子"),
            ("intelligent", "adj.", "聪明的"),
            ("intense", "adj.", "强烈的；紧张的"),
            ("intensive", "adj.", "密集的；深入的"),
            ("intentional", "adj.", "故意的"),
            ("interesting", "adj.", "有趣的"),
            ("internal", "adj.", "内部的"),
            ("international", "adj.", "国际的"),
            ("intimate", "adj./v.", "亲密的；暗示"),
            ("intrinsic", "adj.", "内在的；本质的"),
            ("invaluable", "adj.", "无价的"),
            ("invasive", "adj.", "侵入的"),
            ("inverse", "adj./n.", "相反的；倒数"),
            ("invisible", "adj.", "看不见的"),
            ("involuntary", "adj.", "非自愿的"),
            ("irrelevant", "adj.", "不相关的"),
            ("isolated", "adj.", "孤立的"),
            ("joint", "adj./n.", "联合的；关节"),
            ("just", "adj./adv.", "公正的；正好"),
            ("keen", "adj.", "热衷的；敏锐的"),
            ("knowledgeable", "adj.", "知识渊博的"),
            ("lasting", "adj.", "持久的"),
        ]
    },
    {
        "name": "五、高频副词与介词短语",
        "desc": "完形填空中起状语功能的核心副词和短语",
        "words": [
            ("absolutely", "adv.", "绝对地"),
            ("accordingly", "adv.", "相应地；因此"),
            ("accurately", "adv.", "准确地"),
            ("actively", "adv.", "积极地"),
            ("actually", "adv.", "实际上"),
            ("adequately", "adv.", "充分地"),
            ("aggressively", "adv.", "积极地；侵略地"),
            ("almost", "adv.", "几乎"),
            ("already", "adv.", "已经"),
            ("always", "adv.", "总是"),
            ("annually", "adv.", "每年"),
            ("apparently", "adv.", "显然"),
            ("approximately", "adv.", "大约"),
            ("automatically", "adv.", "自动地"),
            ("barely", "adv.", "几乎不"),
            ("basically", "adv.", "基本上"),
            ("briefly", "adv.", "简要地"),
            ("broadly", "adv.", "广泛地"),
            ("certainly", "adv.", "当然"),
            ("clearly", "adv.", "清楚地"),
            ("closely", "adv.", "密切地；仔细地"),
            ("commonly", "adv.", "通常"),
            ("completely", "adv.", "完全地"),
            ("comprehensively", "adv.", "全面地"),
            ("considerably", "adv.", "相当大地"),
            ("consistently", "adv.", "一贯地"),
            ("constantly", "adv.", "不断地"),
            ("continually", "adv.", "持续地"),
            ("continuously", "adv.", "连续不断地"),
            ("conversely", "adv.", "相反地"),
            ("correctly", "adv.", "正确地"),
            ("critically", "adv.", "批判地；关键地"),
            ("currently", "adv.", "目前"),
            ("decisively", "adv.", "果断地"),
            ("deeply", "adv.", "深深地"),
            ("definitely", "adv.", "肯定地"),
            ("deliberately", "adv.", "故意地"),
            ("dramatically", "adv.", "戏剧性地；显著地"),
            ("effectively", "adv.", "有效地"),
            ("efficiently", "adv.", "高效地"),
            ("enormously", "adv.", "巨大地"),
            ("entirely", "adv.", "完全地"),
            ("equally", "adv.", "平等地；同样地"),
            ("especially", "adv.", "尤其"),
            ("essentially", "adv.", "本质上"),
            ("even", "adv.", "甚至"),
            ("eventually", "adv.", "最终"),
            ("ever", "adv.", "曾经；永远"),
            ("evidently", "adv.", "明显地"),
            ("exactly", "adv.", "确切地"),
            ("excessively", "adv.", "过度地"),
            ("exclusively", "adv.", "排他地；专门地"),
            ("explicitly", "adv.", "明确地"),
            ("extremely", "adv.", "极其"),
            ("fairly", "adv.", "相当；公平地"),
            ("firmly", "adv.", "坚定地"),
            ("firstly", "adv.", "首先"),
            ("forcibly", "adv.", "强制地"),
            ("formally", "adv.", "正式地"),
            ("formerly", "adv.", "以前"),
            ("frequently", "adv.", "频繁地"),
            ("fully", "adv.", "完全地"),
            ("further", "adv./adj./v.", "进一步；促进"),
            ("furthermore", "adv.", "此外"),
            ("generally", "adv.", "通常；一般地"),
            ("gradually", "adv.", "逐渐地"),
            ("greatly", "adv.", "大大地"),
            ("hardly", "adv.", "几乎不"),
            ("heavily", "adv.", "沉重地；大量地"),
            ("highly", "adv.", "高度地；非常"),
            ("immediately", "adv.", "立即"),
            ("immensely", "adv.", "巨大地"),
            ("increasingly", "adv.", "越来越"),
            ("indeed", "adv.", "确实"),
            ("inevitably", "adv.", "不可避免地"),
            ("initially", "adv.", "起初"),
            ("instantly", "adv.", "立即"),
            ("intensely", "adv.", "强烈地"),
            ("largely", "adv.", "主要地；很大程度上"),
            ("lately", "adv.", "最近"),
            ("literally", "adv.", "字面上；确实"),
            ("mainly", "adv.", "主要地"),
            ("merely", "adv.", "仅仅"),
            ("mostly", "adv.", "大多数；主要"),
            ("namely", "adv.", "即"),
            ("naturally", "adv.", "自然地"),
            ("nearly", "adv.", "几乎"),
            ("necessarily", "adv.", "必要地"),
            ("nevertheless", "adv.", "然而"),
            ("nonetheless", "adv.", "尽管如此"),
            ("normally", "adv.", "通常"),
            ("obviously", "adv.", "明显地"),
            ("occasionally", "adv.", "偶尔"),
            ("openly", "adv.", "公开地"),
            ("originally", "adv.", "最初"),
            ("particularly", "adv.", "特别地"),
            ("partly", "adv.", "部分地"),
            ("permanently", "adv.", "永久地"),
            ("persistently", "adv.", "持续地"),
            ("personally", "adv.", "个人地"),
            ("physically", "adv.", "身体上；物理上"),
            ("positively", "adv.", "积极地"),
            ("precisely", "adv.", "精确地"),
            ("predominantly", "adv.", "主要地"),
            ("primarily", "adv.", "主要地；首先"),
            ("principally", "adv.", "主要地"),
            ("privately", "adv.", "私人地"),
            ("probably", "adv.", "很可能"),
            ("promptly", "adv.", "迅速地"),
            ("properly", "adv.", "适当地"),
            ("proportionally", "adv.", "按比例地"),
            ("publicly", "adv.", "公开地"),
            ("purely", "adv.", "纯粹地"),
            ("randomly", "adv.", "随机地"),
            ("rapidly", "adv.", "迅速地"),
            ("rarely", "adv.", "很少"),
            ("readily", "adv.", "乐意地；轻易地"),
            ("reasonably", "adv.", "合理地"),
            ("recently", "adv.", "最近"),
            ("regardless", "adv.", "不管怎样"),
            ("regularly", "adv.", "有规律地"),
            ("relatively", "adv.", "相对地"),
            ("remarkably", "adv.", "显著地"),
            ("repeatedly", "adv.", "重复地"),
            ("respectively", "adv.", "分别地"),
            ("roughly", "adv.", "大致"),
            ("routinely", "adv.", "例行地"),
            ("scarcely", "adv.", "几乎不"),
            ("seldom", "adv.", "很少"),
            ("severely", "adv.", "严重地"),
            ("sharply", "adv.", "急剧地"),
            ("shortly", "adv.", "不久"),
            ("significantly", "adv.", "显著地"),
            ("similarly", "adv.", "类似地"),
            ("simply", "adv.", "简单地；仅仅"),
            ("simultaneously", "adv.", "同时地"),
            ("slightly", "adv.", "轻微地"),
            ("slowly", "adv.", "缓慢地"),
            ("smoothly", "adv.", "平滑地；顺利地"),
            ("so-called", "adj.", "所谓的"),
            ("solely", "adv.", "唯一地；仅"),
            ("specifically", "adv.", "具体地"),
            ("steadily", "adv.", "稳定地"),
            ("strictly", "adv.", "严格地"),
            ("strongly", "adv.", "强烈地"),
            ("subsequently", "adv.", "随后"),
            ("substantially", "adv.", "实质上；大量地"),
            ("successfully", "adv.", "成功地"),
            ("sufficiently", "adv.", "足够地"),
            ("suitably", "adv.", "适当地"),
            ("supposedly", "adv.", "据称"),
            ("surely", "adv.", "肯定地"),
            ("surprisingly", "adv.", "令人惊讶地"),
            ("thoroughly", "adv.", "彻底地"),
            ("thus", "adv.", "因此"),
            ("tightly", "adv.", "紧紧地"),
            ("totally", "adv.", "完全地"),
            ("truly", "adv.", "真正地"),
            ("typically", "adv.", "典型地"),
            ("ultimately", "adv.", "最终"),
            ("unanimously", "adv.", "一致地"),
            ("undoubtedly", "adv.", "无疑地"),
            ("unexpectedly", "adv.", "意外地"),
            ("uniformly", "adv.", "一致地"),
            ("universally", "adv.", "普遍地"),
            ("utterly", "adv.", "完全地"),
            ("vaguely", "adv.", "模糊地"),
            ("variously", "adv.", "不同地"),
            ("virtually", "adv.", "几乎；虚拟地"),
            ("visibly", "adv.", "明显地"),
            ("voluntarily", "adv.", "自愿地"),
            ("wholly", "adv.", "完全地"),
            ("widely", "adv.", "广泛地"),
            ("at all", "adv.", "根本，完全"),
            ("by all means", "adv.", "尽一切办法"),
            ("by no means", "adv.", "绝不"),
            ("in no case", "adv.", "绝不"),
            ("on no account", "adv.", "绝不"),
            ("in any case", "adv.", "无论如何"),
            ("at any rate", "adv.", "无论如何"),
            ("in any event", "adv.", "无论如何"),
            ("at once", "adv.", "立刻；同时"),
            ("at first", "adv.", "起初"),
            ("at last", "adv.", "最后"),
            ("at least", "adv.", "至少"),
            ("at most", "adv.", "至多"),
            ("at present", "adv.", "目前"),
            ("at times", "adv.", "有时"),
            ("in time", "adv.", "及时"),
            ("on time", "adv.", "准时"),
            ("in no time", "adv.", "很快"),
            ("from time to time", "adv.", "不时"),
            ("once in a while", "adv.", "偶尔"),
            ("all of a sudden", "adv.", "突然"),
            ("by chance", "adv.", "偶然"),
            ("by accident", "adv.", "偶然"),
            ("on purpose", "adv.", "故意地"),
            ("in particular", "adv.", "特别地"),
            ("in general", "adv.", "总的来说"),
            ("in short", "adv.", "简言之"),
            ("in brief", "adv.", "简而言之"),
            ("in detail", "adv.", "详细地"),
            ("in turn", "adv.", "依次；反过来"),
            ("in return", "adv.", "作为回报"),
            ("in vain", "adv.", "徒劳地"),
            ("in advance", "adv.", "提前"),
            ("in case", "conj.", "以防"),
            ("in addition to", "prep.", "除…之外"),
            ("apart from", "prep.", "除…之外"),
            ("aside from", "prep.", "除…之外"),
            ("except for", "prep.", "除…之外"),
            ("other than", "prep.", "除…之外；不同于"),
            ("rather than", "conj.", "而不是"),
            ("more than", "adv.", "多于；非常"),
            ("no more than", "adv.", "仅仅"),
            ("not more than", "adv.", "不超过"),
            ("no less than", "adv.", "不少于"),
            ("as well as", "conj.", "以及"),
            ("not only...but also", "conj.", "不仅…而且"),
            ("either...or", "conj.", "要么…要么"),
            ("neither...nor", "conj.", "既不…也不"),
            ("both...and", "conj.", "两者都"),
            ("so...as to", "conj.", "如此…以至于"),
            ("such...that", "conj.", "如此…以至于"),
            ("so that", "conj.", "以便；所以"),
            ("in order to", "adv.", "为了"),
            ("now that", "conj.", "既然"),
            ("as long as", "conj.", "只要"),
            ("as far as", "conj.", "就…而言"),
            ("as soon as", "conj.", "一…就"),
            ("as if", "conj.", "仿佛"),
            ("as though", "conj.", "仿佛"),
            ("even if", "conj.", "即使"),
            ("even though", "conj.", "即使"),
            ("what if", "conj.", "如果…会怎样"),
        ]
    },
    {
        "name": "六、固定搭配与短语动词",
        "desc": "完形填空必考固定搭配，尤其是介词搭配和动词短语",
        "words": [
            ("accuse of", "v.", "指控"),
            ("adapt to", "v.", "适应"),
            ("add to", "v.", "增加"),
            ("adhere to", "v.", "坚持；遵守"),
            ("agree with", "v.", "同意（人）"),
            ("agree on", "v.", "就…达成一致"),
            ("agree to", "v.", "同意（计划）"),
            ("aim at", "v.", "旨在；瞄准"),
            ("apologize for", "v.", "为…道歉"),
            ("appeal to", "v.", "呼吁；吸引"),
            ("apply for", "v.", "申请"),
            ("apply to", "v.", "适用于"),
            ("approve of", "v.", "赞成"),
            ("associate with", "v.", "与…关联"),
            ("base on", "v.", "基于"),
            ("believe in", "v.", "相信"),
            ("belong to", "v.", "属于"),
            ("benefit from", "v.", "从…受益"),
            ("blame for", "v.", "因…责备"),
            ("blame on", "v.", "把…归咎于"),
            ("break down", "v.", "分解；故障"),
            ("break off", "v.", "中断；折断"),
            ("break out", "v.", "爆发"),
            ("break through", "v.", "突破"),
            ("break up", "v.", "分手；打碎"),
            ("bring about", "v.", "引起"),
            ("bring forward", "v.", "提出；提前"),
            ("bring up", "v.", "养育；提出"),
            ("build up", "v.", "积累；增强"),
            ("call for", "v.", "需要；呼吁"),
            ("call off", "v.", "取消"),
            ("call on", "v.", "号召；拜访"),
            ("call up", "v.", "唤起；打电话"),
            ("care about", "v.", "关心"),
            ("carry on", "v.", "继续"),
            ("carry out", "v.", "执行；实施"),
            ("catch up with", "v.", "赶上"),
            ("check in", "v.", "登记入住"),
            ("check out", "v.", "退房；检查"),
            ("come about", "v.", "发生"),
            ("come across", "v.", "偶然遇到"),
            ("come out", "v.", "出来；出版"),
            ("come up", "v.", "发生；被提出"),
            ("come up with", "v.", "想出"),
            ("compare to", "v.", "比作"),
            ("compare with", "v.", "与…比较"),
            ("compensate for", "v.", "赔偿；弥补"),
            ("compete with", "v.", "与…竞争"),
            ("complain about", "v.", "抱怨"),
            ("concentrate on", "v.", "专注于"),
            ("consist of", "v.", "由…组成"),
            ("consist in", "v.", "在于"),
            ("contribute to", "v.", "贡献；导致"),
            ("cope with", "v.", "应对"),
            ("count on", "v.", "指望"),
            ("cover up", "v.", "掩盖"),
            ("cut down", "v.", "削减"),
            ("cut off", "v.", "切断"),
            ("deal with", "v.", "处理"),
            ("depend on", "v.", "依赖；取决于"),
            ("devote to", "v.", "致力于"),
            ("die out", "v.", "灭绝"),
            ("differ from", "v.", "不同于"),
            ("distinguish from", "v.", "区分"),
            ("draw up", "v.", "起草"),
            ("dress up", "v.", "打扮"),
            ("drop out", "v.", "辍学；退出"),
            ("dwell on", "v.", "详述；细想"),
            ("engage in", "v.", "从事"),
            ("equip with", "v.", "配备"),
            ("exchange for", "v.", "交换"),
            ("experiment on", "v.", "在…上实验"),
            ("expose to", "v.", "暴露于"),
            ("face up to", "v.", "勇敢面对"),
            ("fall behind", "v.", "落后"),
            ("fall into", "v.", "落入；属于"),
            ("figure out", "v.", "弄清楚"),
            ("fill in", "v.", "填充"),
            ("find out", "v.", "查明"),
            ("focus on", "v.", "集中"),
            ("get along with", "v.", "与…相处"),
            ("get over", "v.", "克服；恢复"),
            ("get rid of", "v.", "摆脱"),
            ("get through", "v.", "通过；完成"),
            ("give away", "v.", "赠送；泄露"),
            ("give in", "v.", "屈服"),
            ("give off", "v.", "发出（光/气）"),
            ("give out", "v.", "分发；耗尽"),
            ("give up", "v.", "放弃"),
            ("go after", "v.", "追逐"),
            ("go ahead", "v.", "继续"),
            ("go through", "v.", "经历；检查"),
            ("hand in", "v.", "上交"),
            ("hand out", "v.", "分发"),
            ("hang on", "v.", "坚持；稍等"),
            ("hold back", "v.", "阻止；隐瞒"),
            ("hold on", "v.", "坚持；别挂"),
            ("hold up", "v.", "举起；耽搁"),
            ("insist on", "v.", "坚持"),
            ("interfere with", "v.", "干涉"),
            ("interfere in", "v.", "干预"),
            ("keep on", "v.", "继续"),
            ("keep up with", "v.", "跟上"),
            ("knock down", "v.", "击倒"),
            ("lay off", "v.", "解雇；停止"),
            ("lead to", "v.", "导致"),
            ("leave behind", "v.", "留下；落后"),
            ("leave out", "v.", "遗漏"),
            ("lie in", "v.", "在于"),
            ("live on", "v.", "靠…生活"),
            ("live up to", "v.", "不辜负"),
            ("look after", "v.", "照顾"),
            ("look down upon", "v.", "看不起"),
            ("look forward to", "v.", "期待"),
            ("look into", "v.", "调查"),
            ("look up", "v.", "查阅"),
            ("look up to", "v.", "尊敬"),
            ("make for", "v.", "走向；促成"),
            ("make out", "v.", "辨认；理解"),
            ("make up", "v.", "组成；编造"),
            ("make up for", "v.", "弥补"),
            ("make use of", "v.", "利用"),
            ("object to", "v.", "反对"),
            ("occur to", "v.", "想到"),
            ("operate on", "v.", "给…做手术"),
            ("participate in", "v.", "参与"),
            ("pass away", "v.", "去世"),
            ("pass by", "v.", "经过"),
            ("pay attention to", "v.", "注意"),
            ("pay off", "v.", "还清；成功"),
            ("persist in", "v.", "坚持"),
            ("pick out", "v.", "挑选"),
            ("pick up", "v.", "拾起；接人；学会"),
            ("point out", "v.", "指出"),
            ("prefer to", "v.", "偏爱"),
            ("prevent from", "v.", "阻止"),
            ("provide with", "v.", "提供"),
            ("put aside", "v.", "搁置；储蓄"),
            ("put forward", "v.", "提出"),
            ("put off", "v.", "推迟"),
            ("put up with", "v.", "忍受"),
            ("refer to", "v.", "提到；参考"),
            ("relate to", "v.", "与…相关"),
            ("rely on", "v.", "依赖"),
            ("remind of", "v.", "提醒"),
            ("resort to", "v.", "诉诸；求助"),
            ("respond to", "v.", "回应"),
            ("result in", "v.", "导致"),
            ("result from", "v.", "由…引起"),
            ("run out of", "v.", "用尽"),
            ("set about", "v.", "开始做"),
            ("set aside", "v.", "留出；驳回"),
            ("set out", "v.", "出发；开始"),
            ("set up", "v.", "设立"),
            ("settle down", "v.", "定居；安定"),
            ("show off", "v.", "炫耀"),
            ("show up", "v.", "出现"),
            ("speed up", "v.", "加速"),
            ("stand for", "v.", "代表"),
            ("stand out", "v.", "突出"),
            ("stick to", "v.", "坚持"),
            ("take advantage of", "v.", "利用"),
            ("take after", "v.", "像（长辈）"),
            ("take care of", "v.", "照顾"),
            ("take in", "v.", "吸收；欺骗"),
            ("take off", "v.", "起飞；脱下"),
            ("take on", "v.", "承担；呈现"),
            ("take over", "v.", "接管"),
            ("take part in", "v.", "参加"),
            ("take place", "v.", "发生"),
            ("take up", "v.", "占据；开始从事"),
            ("tell from", "v.", "区分"),
            ("think about", "v.", "考虑"),
            ("think over", "v.", "仔细考虑"),
            ("turn down", "v.", "拒绝；调低"),
            ("turn into", "v.", "变成"),
            ("turn off", "v.", "关掉"),
            ("turn on", "v.", "打开"),
            ("turn out", "v.", "结果是；生产"),
            ("turn over", "v.", "移交；翻转"),
            ("turn to", "v.", "求助于"),
            ("turn up", "v.", "出现；调高"),
            ("use up", "v.", "用尽"),
            ("wait for", "v.", "等待"),
            ("warm up", "v.", "热身"),
            ("watch out for", "v.", "提防"),
            ("wear out", "v.", "穿破；筋疲力尽"),
            ("work out", "v.", "解决；锻炼"),
            ("worry about", "v.", "担心"),
            ("write off", "v.", "注销；认为失败"),
            ("account for", "v.", "解释；占（比例）"),
            ("allow for", "v.", "考虑到"),
            ("answer for", "v.", "对…负责"),
            ("ask for", "v.", "请求"),
            ("back up", "v.", "支持；备份"),
            ("become of", "v.", "发生（人或事）"),
            ("begin with", "v.", "以…开始"),
            ("believe in", "v.", "信任"),
            ("blow up", "v.", "爆炸"),
            ("bump into", "v.", "撞上；偶遇"),
            ("burst into", "v.", "突然爆发"),
            ("calm down", "v.", "冷静下来"),
            ("care for", "v.", "照顾；喜欢"),
            ("carry out", "v.", "执行"),
            ("clear up", "v.", "清理；放晴"),
            ("close down", "v.", "关闭"),
            ("comment on", "v.", "评论"),
            ("communicate with", "v.", "与…交流"),
            ("compare with", "v.", "比较"),
            ("compete for", "v.", "竞争"),
            ("connect with", "v.", "与…连接"),
            ("consent to", "v.", "同意"),
            ("consist in", "v.", "在于"),
            ("consult with", "v.", "协商"),
            ("contribute to", "v.", "贡献；投稿"),
            ("cooperate with", "v.", "合作"),
            ("correspond to", "v.", "对应"),
            ("crash into", "v.", "撞上"),
            ("cure of", "v.", "治愈"),
            ("date back to", "v.", "追溯到"),
            ("deal in", "v.", "经营"),
            ("decide on", "v.", "决定"),
            ("delight in", "v.", "以…为乐"),
            ("depart from", "v.", "背离"),
            ("deprive of", "v.", "剥夺"),
            ("derive from", "v.", "源自"),
            ("despair of", "v.", "绝望"),
            ("dispose of", "v.", "处理；去掉"),
            ("dream of", "v.", "梦想"),
            ("end up", "v.", "最终成为"),
            ("enter for", "v.", "报名参加"),
            ("excuse from", "v.", "免除"),
            ("fade away", "v.", "逐渐消失"),
            ("feed on", "v.", "以…为食"),
            ("feel like", "v.", "想要"),
            ("fight against", "v.", "对抗"),
            ("fill up", "v.", "装满"),
            ("finish up", "v.", "完成；结束"),
            ("fit in with", "v.", "适应"),
            ("follow up", "v.", "跟进"),
        ]
    },
    {
        "name": "七、形近词与易混词辨析",
        "desc": "完形填空最易失分的形近/近义词对比，务必掌握",
        "words": [
            ("affect / effect", "v./n.", "影响（v.）/ 效果（n.）"),
            ("accept / except", "v./prep.", "接受 / 除…之外"),
            ("adapt / adopt", "v.", "适应；改编 / 采用；收养"),
            ("angel / angle", "n.", "天使 / 角度"),
            ("assure / ensure / insure", "v.", "使确信 / 确保 / 投保"),
            ("beside / besides", "prep./adv.", "在…旁边 / 此外"),
            ("breath / breathe", "n./v.", "呼吸（n.）/ 呼吸（v.）"),
            ("clash / crash / crush", "v.", "冲突 / 碰撞 / 压碎"),
            ("complement / compliment", "v./n.", "补充 / 赞美"),
            ("conscience / conscious", "n./adj.", "良心 / 有意识的"),
            ("considerable / considerate", "adj.", "相当大的 / 体贴的"),
            ("continual / continuous", "adj.", "频繁的 / 连续不断的"),
            ("council / counsel / consul", "n.", "委员会 / 建议；律师 / 领事"),
            ("critic / critical / crisis", "n./adj./n.", "批评家 / 批评的；关键的 / 危机"),
            ("custom / customs / costume", "n.", "习惯 / 海关 / 服装"),
            ("dairy / diary", "n.", "乳制品 / 日记"),
            ("decent / descend / descent", "adj./v./n.", "体面的 / 下降 / 下降；血统"),
            ("desert / dessert", "n./v./n.", "沙漠；抛弃 / 甜点"),
            ("distract / contract / abstract", "v./n./adj.", "分心 / 合同；收缩 / 摘要；抽象的"),
            ("economic / economical", "adj.", "经济的 / 节约的"),
            ("efficient / effective", "adj.", "高效的 / 有效的"),
            ("emigrate / immigrate", "v.", "移出 / 移入"),
            ("eminent / imminent / imminent", "adj.", "杰出的 / 迫近的"),
            ("employer / employee", "n.", "雇主 / 雇员"),
            ("exhausting / exhausted / exhaustive", "adj.", "令人筋疲力尽的 / 筋疲力尽的 / 详尽无遗的"),
            ("explicit / implicit", "adj.", "明确的 / 隐含的"),
            ("extensive / intensive", "adj.", "广泛的 / 密集的"),
            ("favorite / favorable", "adj.", "最喜欢的 / 有利的；赞同的"),
            ("formally / formerly", "adv.", "正式地 / 以前"),
            ("historic / historical", "adj.", "有历史意义的 / 历史的"),
            ("imaginary / imaginative / imaginable", "adj.", "虚构的 / 富有想象力的 / 可想象的"),
            ("industrial / industrious", "adj.", "工业的 / 勤奋的"),
            ("ingenious / ingenuous", "adj.", "巧妙的；聪明的 / 天真的；坦率的"),
            ("intelligent / intelligible", "adj.", "聪明的 / 可理解的"),
            ("invaluable / valueless", "adj.", "无价的 / 没有价值的"),
            ("later / latter / latest / lately", "adv./adj./adv.", "后来 / 后者的 / 最新的 / 最近"),
            ("lie / lay / lain / laid", "v.", "躺（lie-lay-lain）/ 放置（lay-laid-laid）"),
            ("loose / lose / loss / lost", "adj./v./n./adj.", "松的 / 丢失 / 损失 / 丢失的"),
            ("moral / morale", "adj./n.", "道德的；寓意 / 士气"),
            ("personal / personnel", "adj./n.", "个人的 / 人员；人事"),
            ("perspective / prospective", "n./adj.", "视角；观点 / 预期的；未来的"),
            ("policy / polity", "n.", "政策 / 政体"),
            ("practical / practicable", "adj.", "实际的 / 可行的"),
            ("precede / proceed / proceed", "v.", "先于 / 继续"),
            ("principal / principle", "n./adj./n.", "校长；主要的 / 原则"),
            ("privilege / poverty", "n.", "特权 / 贫穷"),
            ("quiet / quite / quit", "adj./adv./v.", "安静的 / 相当 / 放弃"),
            ("respectable / respectful / respective", "adj.", "可敬的 / 表示尊敬的 / 各自的"),
            ("rise / raise / arise", "v.", "上升 / 提高 / 出现"),
            ("rob / steal", "v.", "抢劫（rob sb of sth）/ 偷窃（steal sth from sb）"),
            ("sensitive / sensible / sensory", "adj.", "敏感的 / 明智的 / 感觉的"),
            ("shortage / shortcut", "n.", "短缺 / 捷径"),
            ("sight / site / cite", "n./v.", "视力；景象 / 地点 / 引用"),
            ("social / sociable", "adj.", "社会的 / 好交际的"),
            ("source / resource / sauce", "n.", "来源 / 资源 / 酱汁"),
            ("special / specific / particular", "adj.", "特殊的 / 具体的 / 特别的"),
            ("statue / status / statute", "n.", "雕像 / 地位 / 法令"),
            ("stormy / storming / stormed", "adj./v.", "暴风雨的 / 猛攻 / 被猛攻的"),
            ("succeed / success / successive", "v./n./adj.", "成功；接替 / 成功 / 连续的"),
            ("superficial / superfluous", "adj.", "表面的 / 多余的"),
            ("tend / tend to / intend", "v.", "倾向 / 照顾 / 打算"),
            ("tour / tourist / tourism", "n./v.", "旅游 / 游客 / 旅游业"),
            ("urban / urgent / urge", "adj./v.", "城市的 / 紧急的 / 催促"),
            ("vacation / vocation / avocation", "n.", "假期 / 职业 / 业余爱好"),
            ("weather / whether", "n./conj.", "天气 / 是否"),
            ("worth / worthy / worthwhile", "adj./n./adj.", "值…的；价值 / 值得的 / 值得做的"),
        ]
    },
    {
        "name": "八、完形填空常考学术词汇",
        "desc": "考研完型常见于社科、科技类文章的学术词",
        "words": [
            ("academic", "adj./n.", "学术的；学者"),
            ("access", "n./v.", "通道；访问"),
            ("accommodate", "v.", "容纳；适应"),
            ("accumulate", "v.", "积累"),
            ("accurate", "adj.", "准确的"),
            ("achieve", "v.", "实现"),
            ("acknowledge", "v.", "承认"),
            ("acquisition", "n.", "获得；习得"),
            ("adequate", "adj.", "充分的"),
            ("adjust", "v.", "调整"),
            ("administration", "n.", "管理；行政"),
            ("advance", "v./n.", "前进；进步"),
            ("adverse", "adj.", "不利的"),
            ("advocate", "v./n.", "提倡；提倡者"),
            ("aggregate", "v./adj./n.", "总计；总的；总数"),
            ("allocation", "n.", "分配"),
            ("alternative", "n./adj.", "替代方案；替代的"),
            ("amend", "v.", "修订；修正"),
            ("analysis", "n.", "分析"),
            ("annual", "adj./n.", "年度；年刊"),
            ("apparent", "adj.", "明显的"),
            ("appreciate", "v.", "欣赏；感激；升值"),
            ("approach", "v./n.", "接近；方法"),
            ("appropriate", "adj./v.", "适当的；拨出"),
            ("artificial", "adj.", "人工的"),
            ("assess", "v.", "评估"),
            ("assign", "v.", "分配；指定"),
            ("assume", "v.", "假定；承担"),
            ("available", "adj.", "可获得的"),
            ("awareness", "n.", "意识"),
            ("barrier", "n.", "障碍"),
            ("bias", "n./v.", "偏见"),
            ("budget", "n./v./adj.", "预算；编预算；廉价的"),
            ("capacity", "n.", "能力；容量"),
            ("category", "n.", "类别"),
            ("chapter", "n.", "章节"),
            ("circumstance", "n.", "环境；情况"),
            ("civilization", "n.", "文明"),
            ("clarify", "v.", "澄清"),
            ("classify", "v.", "分类"),
            ("cognitive", "adj.", "认知的"),
            ("collapse", "v./n.", "崩溃；倒塌"),
            ("commerce", "n.", "商业；贸易"),
            ("commitment", "n.", "承诺；奉献"),
            ("commodity", "n.", "商品"),
            ("compensation", "n.", "补偿"),
            ("component", "n./adj.", "组件；组成的"),
            ("concentrate", "v.", "集中"),
            ("concept", "n.", "概念"),
            ("confine", "v.", "限制"),
            ("conflict", "n./v.", "冲突"),
            ("consequence", "n.", "结果"),
            ("conservation", "n.", "保护；保存"),
            ("constitute", "v.", "构成；建立"),
            ("consume", "v.", "消费"),
            ("contemporary", "adj./n.", "当代的；同代人"),
            ("contribute", "v.", "贡献；导致"),
            ("controversy", "n.", "争议"),
            ("conventional", "adj.", "传统的"),
            ("conversely", "adv.", "相反地"),
            ("convince", "v.", "说服"),
            ("corporate", "adj.", "公司的；团体的"),
            ("correspond", "v.", "对应；通信"),
            ("criteria", "n.", "标准（pl.）"),
            ("crucial", "adj.", "关键的"),
            ("currency", "n.", "货币；流通"),
            ("decade", "n.", "十年"),
            ("decline", "v./n.", "下降；衰退"),
            ("dedicate", "v.", "致力于"),
            ("defeat", "v./n.", "击败"),
            ("defend", "v.", "防御；辩护"),
            ("deficit", "n.", "赤字；缺乏"),
            ("democracy", "n.", "民主"),
            ("demonstrate", "v.", "证明；展示"),
            ("depict", "v.", "描绘"),
            ("deprive", "v.", "剥夺"),
            ("derive", "v.", "源自"),
            ("deserve", "v.", "值得"),
            ("destination", "n.", "目的地"),
            ("destruction", "n.", "破坏"),
            ("determination", "n.", "决心；决定"),
            ("device", "n.", "设备；手段"),
            ("dimension", "n.", "维度；尺寸"),
            ("diminish", "v.", "减少"),
            ("discipline", "n./v.", "纪律；学科"),
            ("discount", "n./v.", "折扣；打折扣"),
            ("discrimination", "n.", "歧视；辨别"),
            ("displace", "v.", "取代；转移"),
            ("display", "v./n.", "展示"),
            ("dispute", "v./n.", "争论"),
            ("dissolve", "v.", "溶解；解散"),
            ("distinction", "n.", "区别；优秀"),
            ("distort", "v.", "扭曲"),
            ("distribution", "n.", "分配；分布"),
            ("diverse", "adj.", "多样的"),
            ("document", "n./v.", "文件；记录"),
            ("domain", "n.", "领域"),
            ("domestic", "adj.", "国内的；家庭的"),
            ("dominate", "v.", "主导；支配"),
            ("draft", "n./v.", "草案；起草"),
            ("duration", "n.", "持续时间"),
            ("dynamic", "adj./n.", "动态的；动力"),
            ("ecology", "n.", "生态"),
            ("economics", "n.", "经济学"),
            ("eliminate", "v.", "消除"),
            ("emerge", "v.", "出现；浮现"),
            ("emission", "n.", "排放；发行"),
            ("empirical", "adj.", "经验主义的"),
            ("encounter", "v./n.", "遭遇"),
            ("enforcement", "n.", "执行；强制"),
            ("enterprise", "n.", "企业；事业"),
            ("entity", "n.", "实体"),
            ("entrepreneur", "n.", "企业家"),
            ("environment", "n.", "环境"),
            ("equilibrium", "n.", "均衡；平衡"),
            ("equivalent", "adj./n.", "等价的；等价物"),
            ("establish", "v.", "建立"),
            ("estate", "n.", "房地产；财产"),
            ("estimate", "v./n.", "估计"),
            ("evaluate", "v.", "评估"),
            ("evolve", "v.", "进化；发展"),
            ("exaggerate", "v.", "夸张"),
            ("exceed", "v.", "超过"),
            ("exception", "n.", "例外"),
            ("excess", "n./adj.", "过量；额外的"),
            ("exchange", "v./n.", "交换"),
            ("exclude", "v.", "排除"),
            ("executive", "adj./n.", "执行的；高管"),
            ("exercise", "v./n.", "锻炼；行使"),
            ("exhibit", "v./n.", "展览；展示"),
            ("expand", "v.", "扩展"),
            ("expenditure", "n.", "支出；花费"),
            ("expertise", "n.", "专业知识"),
            ("exploit", "v./n.", "开发；剥削"),
            ("explore", "v.", "探索"),
            ("export", "v./n.", "出口"),
            ("expose", "v.", "暴露"),
            ("extend", "v.", "延伸"),
            ("extensive", "adj.", "广泛的"),
            ("external", "adj.", "外部的"),
            ("extract", "v./n.", "提取；摘录"),
            ("extreme", "adj./n.", "极端的；极端"),
            ("facilitate", "v.", "促进"),
            ("facility", "n.", "设施；便利"),
            ("factor", "n.", "因素"),
            ("feasible", "adj.", "可行的"),
            ("finance", "n./v.", "财政；融资"),
            ("flexible", "adj.", "灵活的"),
            ("fluctuate", "v.", "波动"),
            ("forecast", "v./n.", "预测"),
            ("formula", "n.", "公式；方案"),
            ("foundation", "n.", "基础；基金会"),
            ("fraction", "n.", "分数；一小部分"),
            ("framework", "n.", "框架"),
            ("function", "n./v.", "功能；起作用"),
            ("fund", "n./v.", "资金；资助"),
            ("fundamental", "adj./n.", "基本的；基本原理"),
            ("generate", "v.", "产生；生成"),
            ("global", "adj.", "全球的"),
            ("guarantee", "v./n.", "保证"),
            ("hypothesis", "n.", "假设"),
            ("identical", "adj.", "完全相同的"),
            ("identify", "v.", "识别；确认"),
            ("ignorance", "n.", "无知"),
            ("illustrate", "v.", "说明；举例说明"),
            ("image", "n.", "形象；图像"),
            ("immigrate", "v.", "移入"),
            ("impact", "n./v.", "影响；冲击"),
            ("implement", "v./n.", "实施；工具"),
            ("implication", "n.", "含义；影响"),
            ("impose", "v.", "强加；征（税）"),
            ("impression", "n.", "印象"),
            ("incentive", "n.", "激励"),
            ("incidence", "n.", "发生率"),
            ("incorporate", "v.", "合并；包含"),
            ("indicate", "v.", "表明"),
            ("individual", "adj./n.", "个人的；个人"),
            ("inevitable", "adj.", "不可避免的"),
            ("inference", "n.", "推断"),
            ("inflation", "n.", "通货膨胀"),
            ("influence", "n./v.", "影响"),
            ("infrastructure", "n.", "基础设施"),
            ("initial", "adj./n.", "最初的；首字母"),
            ("initiative", "n.", "主动性；倡议"),
            ("innovation", "n.", "创新"),
            ("institution", "n.", "机构；制度"),
            ("instrument", "n.", "工具；乐器"),
            ("insurance", "n.", "保险"),
            ("integration", "n.", "整合"),
            ("integrity", "n.", "正直；完整性"),
            ("intellectual", "adj./n.", "智力的；知识分子"),
            ("intelligent", "adj.", "聪明的"),
            ("intensity", "n.", "强度"),
            ("interaction", "n.", "互动；相互作用"),
            ("interpret", "v.", "解释；口译"),
            ("intervention", "n.", "干预"),
            ("investigate", "v.", "调查"),
            ("involve", "v.", "涉及；包含"),
            ("irrelevant", "adj.", "不相关的"),
            ("isolate", "v.", "隔离；孤立"),
            ("journal", "n.", "期刊；日记"),
            ("judgment", "n.", "判断；判决"),
            ("justify", "v.", "证明…正确"),
            ("label", "n./v.", "标签；标注"),
            ("laboratory", "n.", "实验室"),
            ("legislation", "n.", "立法"),
            ("legitimate", "adj./v.", "合法的；使合法"),
            ("liberal", "adj.", "自由的；通识的"),
            ("likelihood", "n.", "可能性"),
            ("limitation", "n.", "限制"),
            ("linguistic", "adj.", "语言的"),
            ("literacy", "n.", "读写能力"),
            ("logical", "adj.", "逻辑的"),
            ("maintain", "v.", "维持；主张"),
            ("management", "n.", "管理"),
            ("manipulate", "v.", "操纵；操作"),
            ("manufacture", "v./n.", "制造"),
            ("mechanism", "n.", "机制"),
            ("mental", "adj.", "精神的；心理的"),
            ("methodology", "n.", "方法论"),
            ("migration", "n.", "迁移"),
            ("military", "adj./n.", "军事的；军队"),
            ("minimum", "n./adj.", "最小；最小的"),
            ("modify", "v.", "修改"),
            ("monitor", "v./n.", "监控；监视器"),
            ("monopoly", "n.", "垄断"),
            ("moral", "adj./n.", "道德的；寓意"),
            ("motivate", "v.", "激励"),
            ("mutual", "adj.", "相互的；共同的"),
            ("negotiate", "v.", "谈判"),
            ("network", "n.", "网络"),
            ("neutral", "adj.", "中立的"),
            ("nevertheless", "adv.", "然而"),
            ("norm", "n.", "规范；标准"),
            ("notion", "n.", "概念；看法"),
            ("nuclear", "adj.", "核的"),
            ("objective", "n./adj.", "目标；客观的"),
            ("obligation", "n.", "义务；责任"),
            ("observation", "n.", "观察"),
            ("obtain", "v.", "获得"),
            ("obvious", "adj.", "明显的"),
            ("occupation", "n.", "职业；占领"),
            ("occur", "v.", "发生"),
            ("offend", "v.", "冒犯；违反"),
            ("opponent", "n./adj.", "对手；对立的"),
            ("opportunity", "n.", "机会"),
            ("oppose", "v.", "反对"),
            ("optimistic", "adj.", "乐观的"),
            ("option", "n.", "选择"),
            ("orient", "v./n.", "定位；东方"),
            ("outcome", "n.", "结果"),
            ("output", "n./v.", "产出"),
            ("overall", "adj./adv.", "总体的；总体上"),
            ("overlap", "v./n.", "重叠"),
            ("overseas", "adv./adj.", "海外；海外的"),
            ("panel", "n.", "面板；专家组"),
            ("paradigm", "n.", "范式"),
            ("paradox", "n.", "悖论"),
            ("parallel", "adj./n./v.", "平行的；平行线；与…平行"),
            ("participate", "v.", "参与"),
            ("partnership", "n.", "伙伴关系"),
            ("perceive", "v.", "感知；认为"),
            ("percentage", "n.", "百分比"),
            ("performance", "n.", "表现；表演；性能"),
            ("periodical", "n./adj.", "期刊；周期性的"),
            ("permanent", "adj.", "永久的"),
            ("persistent", "adj.", "持续的；坚持不懈的"),
            ("perspective", "n.", "视角；观点"),
            ("phenomenon", "n.", "现象"),
            ("philosophy", "n.", "哲学；人生观"),
            ("physical", "adj.", "物理的；身体的"),
            ("policy", "n.", "政策"),
            ("politics", "n.", "政治"),
            ("pollution", "n.", "污染"),
            ("population", "n.", "人口"),
            ("portion", "n.", "部分"),
            ("position", "n.", "位置；职位"),
            ("positive", "adj.", "积极的；肯定的"),
            ("potential", "adj./n.", "潜在的；潜力"),
            ("poverty", "n.", "贫困"),
            ("precede", "v.", "先于"),
            ("predict", "v.", "预测"),
            ("preference", "n.", "偏好"),
            ("prejudice", "n./v.", "偏见"),
            ("preserve", "v.", "保存；保护"),
            ("pressure", "n./v.", "压力；施加压力"),
            ("prevail", "v.", "盛行；占上风"),
            ("principle", "n.", "原则"),
            ("priority", "n.", "优先权"),
            ("procedure", "n.", "程序；步骤"),
            ("proceed", "v.", "继续进行"),
            ("process", "n./v.", "过程；处理"),
            ("profession", "n.", "职业；专业"),
            ("professional", "adj./n.", "专业的；专业人士"),
            ("profit", "n./v.", "利润；获益"),
            ("profound", "adj.", "深刻的"),
            ("prohibit", "v.", "禁止"),
            ("project", "n./v.", "项目；投影；计划"),
            ("promote", "v.", "促进；晋升"),
            ("proportion", "n.", "比例"),
            ("prospect", "n./v.", "前景；勘探"),
            ("protocol", "n.", "协议；草案"),
            ("psychology", "n.", "心理学"),
            ("publication", "n.", "出版；出版物"),
            ("purchase", "v./n.", "购买"),
            ("pursue", "v.", "追求；从事"),
            ("qualification", "n.", "资格"),
            ("quote", "v./n.", "引用；报价"),
            ("radical", "adj./n.", "根本的；激进的；激进分子"),
            ("range", "n./v.", "范围；变动"),
            ("rank", "n./v.", "等级；排名"),
            ("rational", "adj.", "理性的"),
            ("react", "v.", "反应"),
            ("realistic", "adj.", "现实的"),
            ("recognition", "n.", "识别；承认"),
            ("recommend", "v.", "推荐"),
            ("recovery", "n.", "恢复；复苏"),
            ("recruit", "v./n.", "招聘；新成员"),
            ("reflect", "v.", "反映；思考"),
            ("reform", "v./n.", "改革"),
            ("region", "n.", "地区"),
            ("register", "v./n.", "注册；登记"),
            ("regulate", "v.", "调节；管理"),
            ("reject", "v.", "拒绝；排斥"),
            ("release", "v./n.", "释放；发布"),
            ("relevant", "adj.", "相关的"),
            ("reliable", "adj.", "可靠的"),
            ("relief", "n.", "缓解；救济"),
            ("religious", "adj.", "宗教的"),
            ("reluctant", "adj.", "不情愿的"),
            ("rely", "v.", "依赖"),
            ("remain", "v.", "保持；剩余"),
            ("remark", "v./n.", "评论；引人注目"),
            ("remedy", "n./v.", "补救；治疗"),
            ("remote", "adj.", "遥远的"),
            ("remove", "v.", "移除"),
            ("renew", "v.", "更新；续约"),
            ("replace", "v.", "取代"),
            ("represent", "v.", "代表"),
            ("reputation", "n.", "名声"),
            ("request", "v./n.", "请求"),
            ("require", "v.", "需要；要求"),
            ("research", "n./v.", "研究"),
            ("reserve", "v./n.", "保留；储备"),
            ("residence", "n.", "住宅；居住"),
            ("resign", "v.", "辞职"),
            ("resist", "v.", "抵抗；抵制"),
            ("resolution", "n.", "决心；解决方案"),
            ("resolve", "v.", "解决；决定"),
            ("resource", "n.", "资源"),
            ("respond", "v.", "回应"),
            ("responsible", "adj.", "负责的"),
            ("restore", "v.", "恢复；修复"),
            ("restrict", "v.", "限制"),
            ("retain", "v.", "保留"),
            ("reveal", "v.", "揭示；透露"),
            ("revenue", "n.", "收入；税收"),
            ("reverse", "v./adj./n.", "逆转；相反的；反面"),
            ("revise", "v.", "修订；复习"),
            ("revolution", "n.", "革命；变革"),
            ("risk", "n./v.", "风险；冒险"),
            ("rival", "n./adj./v.", "对手；竞争的；与…匹敌"),
            ("role", "n.", "角色；作用"),
            ("route", "n.", "路线"),
            ("satisfaction", "n.", "满意"),
            ("scale", "n./v.", "规模；比例；攀登"),
            ("scatter", "v.", "分散；散开"),
            ("schedule", "n./v.", "时间表；安排"),
            ("scheme", "n./v.", "方案；计划"),
            ("scope", "n.", "范围；机会"),
            ("section", "n.", "部分；章节"),
            ("sector", "n.", "部门；行业"),
            ("secure", "adj./v.", "安全的；获得"),
            ("seek", "v.", "寻求"),
            ("segment", "n./v.", "部分；分割"),
            ("select", "v./adj.", "选择；精选的"),
            ("senior", "adj./n.", "资深的；年长的；上级"),
            ("sequence", "n.", "序列；顺序"),
            ("session", "n.", "会议；学期"),
            ("settlement", "n.", "解决；定居点"),
            ("severe", "adj.", "严重的；严厉的"),
            ("shift", "v./n.", "转变；轮班"),
            ("signal", "n./v.", "信号；发信号"),
            ("significance", "n.", "意义；重要性"),
            ("similar", "adj.", "相似的"),
            ("source", "n.", "来源；源头"),
            ("specific", "adj./n.", "具体的；细节"),
            ("stable", "adj./n.", "稳定的；马厩"),
            ("standard", "n./adj.", "标准；标准的"),
            ("status", "n.", "地位；状态"),
            ("strategy", "n.", "策略"),
            ("stress", "n./v.", "压力；强调"),
            ("structure", "n./v.", "结构；构造"),
            ("struggle", "v./n.", "挣扎；斗争"),
            ("subjective", "adj.", "主观的"),
            ("submit", "v.", "提交；服从"),
            ("subsequently", "adv.", "随后"),
            ("subsidy", "n.", "补贴"),
            ("substitute", "v./n.", "替代；替代品"),
            ("sufficient", "adj.", "足够的"),
            ("summarize", "v.", "总结"),
            ("superior", "adj./n.", "优越的；上级"),
            ("supplement", "v./n.", "补充；增补"),
            ("survey", "v./n.", "调查；测量"),
            ("survival", "n.", "生存"),
            ("suspect", "v./n./adj.", "怀疑；嫌疑犯；可疑的"),
            ("sustain", "v.", "维持；支撑"),
            ("symbol", "n.", "象征；符号"),
            ("sympathy", "n.", "同情"),
            ("tackle", "v.", "处理；对付"),
            ("target", "n./v.", "目标；以…为目标"),
            ("task", "n.", "任务"),
            ("technique", "n.", "技术；技巧"),
            ("technology", "n.", "技术；工艺"),
            ("tendency", "n.", "趋势；倾向"),
            ("terminal", "adj./n.", "终端的；终点站"),
            ("territory", "n.", "领土；领域"),
            ("theory", "n.", "理论"),
            ("therapy", "n.", "治疗"),
            ("threat", "n.", "威胁"),
            ("threshold", "n.", "门槛；阈值"),
            ("tolerance", "n.", "容忍；公差"),
            ("trace", "v./n.", "追踪；痕迹"),
            ("tradition", "n.", "传统"),
            ("transfer", "v./n.", "转移；转让"),
            ("transform", "v.", "转变；改造"),
            ("transition", "n.", "过渡；转变"),
            ("transmit", "v.", "传输；传播"),
            ("transparent", "adj.", "透明的"),
            ("transport", "v./n.", "运输"),
            ("trend", "n./v.", "趋势；倾向"),
            ("trigger", "v./n.", "触发；扳机"),
            ("typical", "adj.", "典型的"),
            ("undergo", "v.", "经历"),
            ("undertake", "v.", "承担；从事"),
            ("unemployment", "n.", "失业"),
            ("universe", "n.", "宇宙"),
            ("valid", "adj.", "有效的；合理的"),
            ("vanish", "v.", "消失"),
            ("variable", "adj./n.", "可变的；变量"),
            ("variation", "n.", "变化；变异"),
            ("venture", "n./v.", "企业；冒险"),
            ("version", "n.", "版本"),
            ("victim", "n.", "受害者"),
            ("violation", "n.", "违反；侵犯"),
            ("virtue", "n.", "美德；优点"),
            ("visible", "adj.", "可见的"),
            ("vision", "n.", "视力；愿景"),
            ("vital", "adj.", "至关重要的"),
            ("volume", "n.", "体积；容量；卷"),
            ("voluntary", "adj.", "自愿的"),
            ("vulnerable", "adj.", "脆弱的；易受攻击的"),
            ("welfare", "n./adj.", "福利；福利的"),
            ("widespread", "adj.", "广泛的"),
            ("wisdom", "n.", "智慧"),
            ("withdraw", "v.", "撤回；提取"),
            ("withstand", "v.", "承受；抵挡"),
            ("witness", "n./v.", "目击者；目击"),
            ("workforce", "n.", "劳动力"),
            ("yield", "v./n.", "产出；屈服；产量"),
            ("zone", "n./v.", "区域；划分区域"),
        ]
    },
]

# ── 统计总词数 ────────────────────────────────────────────────
total_words = sum(len(cat["words"]) for cat in CATEGORIES)
print(f"总计 {total_words} 个单词/短语")


class ClozePDF(FPDF):
    """自定义PDF类"""

    def __init__(self):
        super().__init__(orientation="P", unit="mm", format="A4")
        # 注册中文字体
        self.add_font("zh", "", FONT_MAIN)
        self.add_font("zh", "B", FONT_BOLD if os.path.exists(FONT_BOLD) else FONT_HEAD)
        self.add_font("zh_head", "", FONT_HEAD)
        self.set_auto_page_break(auto=True, margin=25)
        self._chapter_page = {}  # 记录每个分类的起始页码

    def header(self):
        if self.page_no() == 1:
            return
        self.set_font("zh", "", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 5, "考研英语完形填空高频1000词", align="L")
        self.cell(0, 5, f"第 {self.page_no()} 页", align="R", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(200, 200, 200)
        self.line(10, 12, 200, 12)
        self.ln(3)

    def footer(self):
        pass  # 不显示页脚

    def cover_page(self):
        """封面页"""
        self.add_page()
        self.ln(50)
        # 主标题
        self.set_font("zh_head", "", 32)
        self.set_text_color(30, 60, 114)
        self.cell(0, 15, "考研英语完形填空", align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 15, "高频核心 1000 词", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(10)
        # 装饰线
        self.set_draw_color(30, 60, 114)
        self.set_line_width(0.8)
        self.line(60, self.get_y(), 150, self.get_y())
        self.ln(15)
        # 副标题
        self.set_font("zh", "", 14)
        self.set_text_color(80, 80, 80)
        self.cell(0, 10, "完形填空 · 高频考点 · 分类记忆", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(5)
        self.set_font("zh", "", 11)
        self.cell(0, 8, f"涵盖 {len(CATEGORIES)} 大分类，共 {total_words} 个核心词条", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(20)
        # 分类预览
        self.set_font("zh", "", 10)
        self.set_text_color(60, 60, 60)
        for cat in CATEGORIES:
            n = len(cat["words"])
            self.cell(0, 7, f"  {cat['name']}  ({n} 词)", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(15)
        self.set_font("zh", "", 9)
        self.set_text_color(140, 140, 140)
        self.cell(0, 6, "2026年7月  ·  考研英语备考资料", align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 6, "基于近10年真题完形填空语料统计分析", align="C", new_x="LMARGIN", new_y="NEXT")

    def section_title(self, cat_name, cat_desc, count):
        """分类标题页"""
        self.add_page()
        self._chapter_page[cat_name] = self.page_no()
        self.set_font("zh_head", "", 18)
        self.set_text_color(30, 60, 114)
        self.cell(0, 12, cat_name, new_x="LMARGIN", new_y="NEXT")
        self.set_font("zh", "", 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 8, f"{cat_desc}  ·  共 {count} 词", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(30, 60, 114)
        self.set_line_width(0.5)
        self.line(10, self.get_y() + 1, 200, self.get_y() + 1)
        self.ln(6)

    def word_table(self, words, cols=2):
        """以表格形式展示单词列表"""
        # 计算每列词数
        per_col = (len(words) + cols - 1) // cols
        for start_row in range(0, per_col, 20):  # 每页最多 20 行
            if start_row > 0:
                self.add_page()
            # 表格头部
            col_w = 95  # 每列宽度
            # 表头
            self.set_font("zh", "B", 9)
            self.set_fill_color(30, 60, 114)
            self.set_text_color(255, 255, 255)
            for c in range(cols):
                x0 = 10 + c * col_w
                self.set_xy(x0, self.get_y())
                self.cell(col_w, 7, f"  单词/短语  词性  释义", border=0, fill=True, align="L")
            self.ln(7)

            # 数据行
            self.set_font("zh", "", 8)
            self.set_text_color(40, 40, 40)
            fill = False
            for i in range(start_row, min(start_row + 20, per_col)):
                y_start = self.get_y()
                row_h = 6.5
                # 检查是否超出页面
                if y_start + row_h > 270:
                    break
                for c in range(cols):
                    idx = i + c * per_col
                    if idx >= len(words):
                        break
                    word, pos, meaning = words[idx]
                    x0 = 10 + c * col_w
                    self.set_xy(x0, y_start)
                    # 交替行背景
                    if fill:
                        self.set_fill_color(245, 245, 250)
                        self.rect(x0, y_start, col_w, row_h, "F")
                    self.set_text_color(40, 40, 40)
                    # 单词
                    self.set_font("zh", "B", 8.5)
                    self.cell(28, row_h, f"  {word}", align="L")
                    # 词性
                    self.set_font("zh", "", 7)
                    self.set_text_color(130, 130, 130)
                    self.cell(12, row_h, pos, align="C")
                    # 释义
                    self.set_font("zh", "", 8)
                    self.set_text_color(60, 60, 60)
                    self.cell(col_w - 40, row_h, meaning, align="L")
                self.set_y(y_start + row_h)
                fill = not fill


# ── 生成 PDF ──────────────────────────────────────────────────
pdf = ClozePDF()

# 1. 封面
pdf.cover_page()

# 2. 目录页
pdf.add_page()
pdf.set_font("zh_head", "", 16)
pdf.set_text_color(30, 60, 114)
pdf.cell(0, 12, "目  录", align="C", new_x="LMARGIN", new_y="NEXT")
pdf.ln(5)
pdf.set_draw_color(30, 60, 114)
pdf.set_line_width(0.5)
pdf.line(50, pdf.get_y(), 160, pdf.get_y())
pdf.ln(8)
pdf.set_font("zh", "", 11)
pdf.set_text_color(60, 60, 60)
for i, cat in enumerate(CATEGORIES, 1):
    n = len(cat["words"])
    pdf.cell(0, 9, f"  {cat['name']} .......................... ({n} 词)", new_x="LMARGIN", new_y="NEXT")
pdf.ln(10)
pdf.set_font("zh", "", 9)
pdf.set_text_color(140, 140, 140)
pdf.cell(0, 7, f"总计：{total_words} 个单词/短语，涵盖完形填空全部考点类型", new_x="LMARGIN", new_y="NEXT")
pdf.cell(0, 7, "建议：每天学习 1-2 个分类，配合真题练习效果更佳", new_x="LMARGIN", new_y="NEXT")

# 3. 各分类正文
for cat in CATEGORIES:
    pdf.section_title(cat["name"], cat["desc"], len(cat["words"]))
    pdf.word_table(cat["words"])

# 4. 附录：索引页
pdf.add_page()
pdf.set_font("zh_head", "", 14)
pdf.set_text_color(30, 60, 114)
pdf.cell(0, 12, "使用说明与学习建议", align="C", new_x="LMARGIN", new_y="NEXT")
pdf.ln(5)
pdf.set_draw_color(30, 60, 114)
pdf.line(50, pdf.get_y(), 160, pdf.get_y())
pdf.ln(8)
pdf.set_font("zh", "", 10)
pdf.set_text_color(60, 60, 60)
tips = [
    "1. 考研英语完形填空共20题，每题0.5分，总分10分。",
    "2. 高频考点：逻辑关系词（约30%）、动词辨析（约25%）、名词辨析（约20%）。",
    "3. 建议先过一遍单词，标记已掌握的词，重点复习生词。",
    "4. 搭配真题练习：做完一篇完形后，将选项中的生词加入复习列表。",
    "5. 特别关注形近词辨析（第7类），这是易失分点。",
    "6. 固定搭配（第6类）需反复记忆，完形常考介词搭配。",
    "",
    "推荐学习顺序：",
    "  第1步：逻辑关系词（掌握文章脉络）",
    "  第2步：高频动词 + 名词（扩充词汇量）",
    "  第3步：固定搭配与短语动词（突破介词题）",
    "  第4步：形近词辨析（精准提分）",
    "  第5步：副词与介词短语 + 学术词汇",
    "",
    "数据来源：近10年考研英语（一/二）完形填空真题语料统计。",
]
for t in tips:
    pdf.cell(0, 7, t, new_x="LMARGIN", new_y="NEXT")

# ── 保存 ──────────────────────────────────────────────────────
output_dir = "E:/wuyi/数学建模半自动/research-assistant/outputs/核心词"
os.makedirs(output_dir, exist_ok=True)
output_path = os.path.join(output_dir, "考研英语完形填空高频1000词.pdf")
pdf.output(output_path)
print(f"\nPDF 已生成：{output_path}")
print(f"  共 {pdf.page_no()} 页，{total_words} 个词条")
